### ISSUE TITLE
callbacks called with same context

### ISSUE THREAD

**Issue by dbaq** [cordova-sms/cordova-sms-plugin#10]
@alvare reported: ```It seems every callback is called with the same context, meaning for example a this binding will reference an old object in a second callback.

This could be caused by having keepCallback(true) before every callbackContext.sendPluginResult
in Sms.java: https://github.com/aharris88/phonegap-sms-plugin/blob/master/src/android/Sms.java#L62```

**Comment by dbaq** [comment]
Hey @alvare, I refactored the android code. This issue should be fixed.

Please test by using the development branch:

```
cordova plugin rm org.apache.cordova.plugin.sms
cordova plugin add https://github.com/cordova-sms/cordova-sms-plugin.git#wip_android_refactoring
```

let me know

**Comment by clrnd** [comment]
It works!
Thanks for your work, and btw the refactor already looks much better!

**Comment by dbaq** [comment]
Ok glad it works.
I will merge this branch soon, waiting to do some other tests.

**Comment by dbaq** [comment]
@alvare, I merged the branch so I am closing this issue. If you notice anything else, please let me know.
