### ISSUE TITLE
unable to send sms in loop

### ISSUE THREAD

**Issue by vitaly87** [cordova-sms/cordova-sms-plugin#100]
Hi,
I am trying to send SMS with loop but it doesn't work,
[http://stackoverflow.com/questions/39740377/how-to-send-sms-with-loop-on-cordova](link to code)

any help?

**Comment by volkovmqx** [comment]
use the success callback function to go to next iteration of the loop

**Comment by vitaly87** [comment]
@volkovmqx hi, I saw that I can pass array of numbers to sms service to send sms, is it have some limits of length?

**Comment by dbaq** [comment]
hello @vitaly87,

> use the success callback function to go to next iteration of the loop

yes, it is the correct way to iterate

> hi, I saw that I can pass array of numbers to sms service to send sms, is it have some limits of length?

yes, you can also pass an array of phone numbers, there is no limit AFAIK.
