### ISSUE TITLE
plugin_not_instaled

### ISSUE THREAD

**Issue by marwanes** [cordova-sms/cordova-sms-plugin#101]
i alredy instaled the plugin but it still doesn't work

**Comment by dbaq** [comment]
Hello @marwanes,

can you please share more information? which platform? how did you install it? etc.

Thank you.

**Comment by vitaly87** [comment]
I am using ionic 2.1.0 and cordova 6+ on  android

**Comment by dbaq** [comment]
Might it be related to #103?

**Comment by dbaq** [comment]
Closing this one since no answer, please reopen if the issue is still happening.
