### ISSUE TITLE
not sending sms to group 

### ISSUE THREAD

**Issue by vitaly87** [cordova-sms/cordova-sms-plugin#102]
Hi all,
I am trying to send to group of people sms but I can see that sms send to only one person...
My code is:

```
   var options = {
          replaceLineBreaks: false, // true to replace \n by a new line, false by default
          android: {
           // intent: 'INTENT'  // send SMS with the native android SMS messaging
            //intent: '' // send SMS without open any other app
          }
        };

        var success = function () { alert('Message sent successfully'); };
        var error = function (e) { alert('Message Failed:' + e); };
        sms.send(['0544462095',.........,'0547549701'],
          $scope.sms.context, options, success, error);

```

I am using ionic 2.1and cordova 6+,
any idea whey? 

[http://stackoverflow.com/questions/39792861/not-sending-sms-more-than-ones]

**Comment by dbaq** [comment]
Hello @vitaly87,

Sending a group text message is not a SMS but a MMS. There is a work in progress that you can contribute to, see #14.

To send one SMS to several people, you can iterate through the array and call the send function.

**Comment by vitaly87** [comment]
That not working you can see example that I added to this post
