### ISSUE TITLE
Package name not in sync with Ionic

### ISSUE THREAD

**Issue by aggarwalankush** [cordova-sms/cordova-sms-plugin#103]
Please see this issue if you can fix it https://github.com/driftyco/ionic-native/issues/643#issuecomment-251839647

**Comment by dbaq** [comment]
hey @aggarwalankush, thanks for reporting the issue. I'll fix the configuration soon. It was for phonegap at that time.

**Comment by dbaq** [comment]
hey @aggarwalankush, thanks again for reporting this issue. I updated both `package.json` and `plugin.xml`, I also published a new version `0.1.11`.

Let me know if you still have the issue.

Cheers.
