### ISSUE TITLE
Sending Multiple Numbers

### ISSUE THREAD

**Issue by josekenya** [cordova-sms/cordova-sms-plugin#107]
I  am trying to send comma separated numbers.However I get an error.How do I go about this?

**Comment by starbassma** [comment]
@josekenya
can you post the error and a snippet of your code ?
Nb: your must split phone numbers with a comma : "," in one string parameter : 

like this : 
$.send(_"_**+11111111111, +111111111112, +2222222222222**_"_, Other parameters)

**Comment by josekenya** [comment]
@starbassma 
I am fetching the contacts from an array like this:
var contacts_array=['+111111111','+22222222','+111111111'];
var contacts_string=contacts_array.toString();
Then:
sms.send(contacts_string,Other params);

Nothing seems to happen.Is this approach correct? 
Also getting an error as well.

**Comment by starbassma** [comment]
@josekenya
No :),
you can do that : 
var contacts_array=['+111111111','+22222222','+111111111'];
var contacts_string=contacts_array.**join**();

**Comment by josekenya** [comment]
@starbassma 
Tried it and still  not working.Just a heads up:
Using android 4.4.2

**Comment by vitaly87** [comment]
I also have similar issue, trying with ionic to send SMS to people and one
first sends can you take a look on my q.

**Comment by vitaly87** [comment]
Only one SMS send to first in the array.

**Comment by agarrharr** [comment]
Check out #50.

**Comment by starbassma** [comment]
@josekenya 
As @aharris88 mentioned it only works if you want to send  MMS, (with intent:'INTENT'), if you want to use it to send multiple sms you must iterate over the phone_numbers array and call $.send each time

**Comment by josekenya** [comment]
@aharris88 @starbassma 
The solution at #50 works great!!However the iterating solution is expensive and may not work as expected. 
Thanks guys :)
