### ISSUE TITLE
doesn't work on iOs 10

### ISSUE THREAD

**Issue by starbassma** [cordova-sms/cordova-sms-plugin#108]
Hello,
i used this wonderful plug-in for almost 1 year, it works perfectly on all Android devices and versions, but it seems that there's a problem with iOs 10, it doesn't show any error and doesn't crash just nothing happened when send() is called,
Nb: the concerned application was built and sent to App store on (Mars 2016) and it work nicely with Ios  6, 7, but as said above it doesn't work with iOs 10.

**Comment by dbaq** [comment]
Hey @starbassma, thanks for the feedback. I'll try to grab an iPhone with iOS 10 on it. In the mean time, can you check if you have any stacktrace in xcode? thank you

**Comment by starbassma** [comment]
@dbaq 
Hello, thank you for your prompt response, but unfortunately i don't have my own mac neither an iphone

**Comment by starbassma** [comment]
Hello @dbaq ,
 any news pleas

**Comment by dbaq** [comment]
hello @starbassma,

sorry for the delay, I had some troubles with Sierra and xcode. I just tried with the sample code on iOS 10.1 and it worked.

```
$ cordova platform
Installed platforms:
  android 5.2.2
  ios 4.3.0
```

```
$ corvoda -v
6.4.0
```

Can you please try again on your side?

**Comment by starbassma** [comment]
Hello @dbaq,
Thanks for your prompt answer, the problem is not related to "cordova-sms" plugin but to  iOS 10 which requires additional entries in the Content-Security-Policy:
adding this tag to my index solved the problem :
`<meta http-equiv="Content-Security-Policy" content="default-src * gap://ready file:; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src * 'unsafe-inline' 'unsafe-eval'">`

Credits to : http://stackoverflow.com/a/38410379

**Comment by dbaq** [comment]
thanks for sharing the solution 👍
