### ISSUE TITLE
Open Default Sms Display When Sending SMS

### ISSUE THREAD

**Issue by radiegtya** [cordova-sms/cordova-sms-plugin#11]
Hi There,

I have question, why when I am sending a sms, it was displaying the default sms display from android? why not just send my message right away without opening the android sms default GUI?

**Comment by dbaq** [comment]
Hey @radiegtya,

I believe that the default behavior was made a long time ago and nobody changed it since. I am not going to change it since it could be a breaking change for a lot of people.

if you need to send a SMS directly, just let the intent parameter empty, see readme:
`sms.send(number, message, '', success, error);`

**Comment by radiegtya** [comment]
Sorry for not reading the documentation in detail. Thanks @dbaq. This is really awesome job :+1: 

Btw do You have reference about reading sms from inbox?

Regards

**Comment by dbaq** [comment]
Thanks @radiegty but I just got the ownership of this repo, you should check out the history section of this plugin, you can find the real heroes there :) (in the readme too)

This plugin is only about sending SMS but I would love to add a support for reading SMS. I believe it would be a great feature, what do you think?

**Comment by radiegtya** [comment]
It will be very great plugin if it was able to:
1. Send SMS with intent
2. Send SMS without intent
3. Send Multipart SMS like native android (this is one of the most important feature)
4. Send Multiple SMS with progress bar (this is not really important, because we still able to send multiple manually with looping)
5. Read SMS from Inbox/Outbox (this is also one of the most important feature)
6. Read Contacts
7. Read Groups Contact

**Comment by agarrharr** [comment]
As far as reading contacts, I would suggest using this plugin: https://github.com/monday-consulting/ContactChooser

I've used the contact chooser plugin to let the user choose a contact and then I used this sms plugin to send the text.

**Comment by dbaq** [comment]
I have also written this plugin: https://github.com/dbaq/cordova-plugin-contacts-phone-numbers

it is an ios/android plugin which was designed to be super fast (compare to the official plugin), it retrieves only the contacts with at least one phone number.

**Comment by radiegtya** [comment]
How About the send sms multipart one? I think it's not solved yet on my latest posted issue

**Comment by dbaq** [comment]
@radiegtya I did some tests today, I can confirm this issue. 

let's follow up there: https://github.com/cordova-sms/cordova-sms-plugin/issues/7

**Comment by leila-net** [comment]
I use sms plugin for cordova , but sent message is not showing in inbox !!! is there any way to add message to inbox or it should be there and my code is incorrect ?

## this is my call for function : 

   var messageInfo = {
                                          phoneNumber: $scope.mobiles[i].mobile,
                                          textMessage: $scope.mobiles[i].message
                                      };

```
                                  sms.sendMessage(messageInfo, function (msg) {

                                  }, function (error) {
                                      alert("code: " + error.code + ", message: " + error.message);
                                  });
```

---

## and the sms plugin :

 public boolean execute(String action, JSONArray args, CallbackContext callbackContext) throws JSONException {
        if (action.equals("sendMessage")) {
            String phoneNumber = args.getString(0);
            String message = args.getString(1);

```
        boolean isSupported = getActivity().getPackageManager().hasSystemFeature(PackageManager.FEATURE_TELEPHONY);

        if (! isSupported) {
            JSONObject errorObject = new JSONObject();

            errorObject.put("code", SMS_FEATURE_NOT_SUPPORTED);
            errorObject.put("message", "SMS feature is not supported on this device");

            callbackContext.sendPluginResult(new PluginResult(Status.ERROR, errorObject));
            return false;
        }

        this.sendSMS(phoneNumber, message, callbackContext);

        ContentValues values = new ContentValues();
         values.put("address", phoneNumber);
         values.put("body", message);
         this.ctx.getContentResolver().insert(Uri.parse("content://sms/sent"), values);

        return true;
    }

    return false;
}
```

**Comment by kqtrinh** [comment]
is there a function just displaying the text message without actually sending. If not are you aware of any plugin out there that shows a text string in an SMS like messages? I mean the nice styllus looking boxes around the text string. Thanks...
