### ISSUE TITLE
Build fails on iOS 10

### ISSUE THREAD

**Issue by RFz2** [cordova-sms/cordova-sms-plugin#110]
Hello,

I'm getting the following output: "File not found #import <Cordova/NSArray+Comparisons.h>" 
This causes iOS builds to fail. Android works fine though. Any ideas?

Many thanks

Ryan

**Comment by dbaq** [comment]
hello @AyeyerMa,

what's your cordova version? try to update it to the latest release.

**Comment by dbaq** [comment]
closing this one since no answer, feel free to reopen it if the problem persists.
