### ISSUE TITLE
problem with permission check 

### ISSUE THREAD

**Issue by Mahmoud85** [cordova-sms/cordova-sms-plugin#111]
Hello Guys
I use a code like this
` $scope.snedNative = function(code, number) {
                $cordovaSms
               .send(number, code, options)
              .then(function() {
               alert('Success');
                  // Success! SMS was sent
                 }, function(error) {
                 alert('Error');
                 // An error occurred
                });
	          console.log("sent");
               }`
the function is working fine , but my problem is that when I run it then android asks me for permission ,and I click cancel, referring to not granting the permission , my function alert success, could anybody help please.

**Comment by RpCoding** [comment]
I guess that has to do with https://github.com/cordova-sms/cordova-sms-plugin/issues/26

**Comment by dbaq** [comment]
Hi @Mahmoud85,

it is weird, if you refuse the permission, you should have an error.

https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/android/Sms.java#L63-L71

I'll dig into this.

**Comment by dbaq** [comment]
Hey @Mahmoud85,

It is working properly, the error callback when I click `Deny` (even several times in a row). It looks like you are using ngCordova or something like that. What's the plugin version?

```
$ cordova plugin ls
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
$ cordova -v
6.4.0
$ cordova platforms
Installed platforms:
  android 5.2.2
  ios 4.3.0
```

![screenshot_20161117-210052](https://cloud.githubusercontent.com/assets/1867703/20419155/26384d24-ad09-11e6-962e-b05ec5edbcc3.png)
![screenshot_20161117-210120](https://cloud.githubusercontent.com/assets/1867703/20419156/264f3336-ad09-11e6-9194-43dd8ad3e794.png)

**Comment by Mahmoud85** [comment]
hello dbaq , appreciate your interest , in fact I'm using ionic.native wrapper and the sms plugin with angular 1 and ionic 1, cordova version 6.3.1 and sms plugin version 0.1.11, please help: 
here is my code and I' m using a real mobile phone.

`$ionicPlatform.ready(function() {

```
    var options = {
     replaceLineBreaks: false, // true to replace \n by a new line, false by default
      android: {
         intent: '' // send SMS with the native android SMS messaging
    //intent: '' // send SMS without open any other app
    //intent: 'INTENT' // send SMS inside a default SMS app
         }
      };

               $scope.sendSMS = function(number, code) {

                   $cordovaSMS
                   .send(number, code, options)
                 .then(function() {
             alert('Success');
             // Success! SMS was sent
            }, function(error) {
             alert('Error');
           // An error occurred
          });
        }`
```

**Comment by Mahmoud85** [comment]
well , I tried it in the emulator , it is working fine but not on a real device, hope you can fix it soon.

**Comment by dbaq** [comment]
try without using ngCordova.

`sms.send(number, code, options, function() {alert('Success');}, function(error) {alert(error);});`

This plugin works correctly (see screenshot). Also, have you checked that you have nothing weird there http://www.greenbot.com/article/2990078/android/how-to-toggle-app-permissions-in-android-marshmallow.html?

**Comment by Mahmoud85** [comment]
when I use it without cordova , android asks for permission to send sms , however neither success nor error functions is fired . I'm so confused about this because I'm using a real device with android 4.4.1, I don't know even why it is asking for permission as per the documentation it is a feature that was developed only on Marshmallow.

**Comment by Mahmoud85** [comment]
it is also working for me in the emulator , the problem occurs only on real device with android 4.4.2 and I don't have a marshmallow device to try it on it.

**Comment by dbaq** [comment]
Closing this one, if it is still an issue, please reopen it.
