### ISSUE TITLE
PGB iOS error on build to cli-6.3.0

### ISSUE THREAD

**Issue by RubenMartins** [cordova-sms/cordova-sms-plugin#115]
HI,

When building an app with cordova cli-6.3.0 on PGB the app crashes to build to iOS I tested from cordova-sms-plugin 0.1.5+
For testing I was able to create the app with your plugin only with cordova cli-5.2.0

Please check this.
Tanks

**Comment by dbaq** [comment]
Hey there, the current plugin version is 0.1.11 https://github.com/cordova-sms/cordova-sms-plugin/blob/master/package.json#L3

Can you try to upgrade?

**Comment by dbaq** [comment]
Any update?

**Comment by RubenMartins** [comment]
Hello, I test all the versions until 0.1.11 and its the same error.

**Comment by dbaq** [comment]
do you have any more information to share? stacktrace? logs?

**Comment by dbaq** [comment]
Closing this once since no answer. Feel free to reopen it.
