### ISSUE TITLE
Cordova Plugins (cordova-sms-plugin) works on Android 4.1.2 but not on Android 4.4.2 (Samsung Galaxy Note GT-N8000)

### ISSUE THREAD

**Issue by karthickv71** [cordova-sms/cordova-sms-plugin#116]
I successfully installed my app, but have a problem with  [cordova-sms-plugin](https://github.com/cordova-sms/cordova-sms-plugin)

It's working on Android 4.1.2 and 6.0.0 but not on 4.4.2 .
When I use the app on Android 4.4.2, the app is working but the plugin does work. I DO get an alert message saying "**SMS is not supported**". So I cannot send an SMS to another mobile,

How can I fix it? do you have anyother sms plugin for Android 4.4.2?

Example code: [Link](https://github.com/cordova-sms/cordova-sms-plugin#using-the-plugin)

**Comment by dbaq** [comment]
Hello @karthickv71,

in your case, this method returns `false`: https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/android/Sms.java#L114-L115

It looks like the `Samsung Galaxy Note GT-N8000` is a tablet, is there a sim card on it?

**Comment by karthickv71** [comment]
Hi dude ..yes there is a simcard on it. I tested on Samsung Galaxy Note GT-N8000. but I Did get an alert message saying "**SMS is not supported**". How can I fix it?

**Comment by dbaq** [comment]
Closing this once since no answer. Feel free to reopen it.
