### ISSUE TITLE
closing app after sending group sms

### ISSUE THREAD

**Issue by vitaly87** [cordova-sms/cordova-sms-plugin#117]
I am trying to send to group sms with cordova-sms-plugin. My issue that all sms sent but the app is closing right after. I am using ionic 1.x,

My code is:
```

.factory("SendSmsAll", function ($cordovaSms, $q) {
    return {
      sendSms: function (contacts, text) {
        //CONFIGURATION
        var options = {
          replaceLineBreaks: false, // true to replace \n by a new line, false by default
          android: {
            // intent: 'INTENT'  // send SMS with the native android SMS messaging
            intent: '' // send SMS without open any other app
          }
        };
        var defer = $q.defer();
        var promises = [];

        function lastTask() {

          var donePopup = $ionicPopup.alert({
            title: 'done sending sms',
            template: 'all sms sent'
          });
          donePopup();
          defer.resolve();
        }

        angular.forEach(contacts.filter(withNumberOnly), function (contact) {
          promises.push($cordovaSms.send(contact.number, text, options, $q.defer().resolve(), $q.defer().reject()));
        });
        function withNumberOnly(contact) {
          return contact.hasOwnProperty('number');
        }

        $q.all(promises).then(lastTask);
        return defer.promise;
      }
```

**Comment by dbaq** [comment]
Please run `adb logcat` on your machine to give me the android stacktrace. That's the only way I can help you.

Thanks.

**Comment by vitaly87** [comment]
I am debug the app via device and chrome on my PC how can I see the log
from chrome?

**Comment by dbaq** [comment]
you have to plug your phone then open the console and run `adb logcat`

**Comment by vitaly87** [comment]
I got this log maybe some help...


12-03 13:46:00.663   786  2700 D SurfaceControl: Excessive delay in
>> setPowerMode(): 217ms
>
> 12-03 13:46:00.671   786  1474 I QCOM PowerHAL: Got set_interactive hint
>
> 12-03 13:46:00.673   786  1474 I PowerManagerService: Sleeping (uid
>> 1000)...
>
> 12-03 13:46:00.738   257  2680 D audio_hw_primary: adev_set_parameters:
>> enter: screen_state=off
>
> 12-03 13:46:00.738   257  2680 E voice   :
>> voice_extn_compress_voip_set_parameters: COMPRESS_VOIP_ENABLED is not
>> defined
>
> 12-03 13:46:00.738   257  2680 E bt_a2dp_hw: adev_set_parameters: ERROR:
>> set param called even when stream out is null
>
> 12-03 13:46:00.738   786  2671 E native  : do suspend true
>
> 12-03 13:46:00.750  3453 31695 E NxpTml  : _i2c_write() errno : 5
>
> 12-03 13:46:00.750  3453 31695 E NxpTml  : PN54X - Error in I2C Write.....
>
> 12-03 13:46:00.750  3453 31697 E NxpHal  : write error status = 0x1ff
>
> 12-03 13:46:00.752  3453 31692 E NxpHal  : write_unlocked failed - PN54X
>> Maybe in Standby Mode - Retry
>
> 12-03 13:46:00.795  2334  2334 I DeviceScanner: [MDNS] Screen is OFF
>
> 12-03 13:46:00.803  2334 27986 W MdnsClient_Cast: Multicast lock held.
>> Releasing. Subtypes:"DCAC4134,D2CA5178"
>
> 12-03 13:46:00.803  2334  2334 I DeviceScanner: [CastNearby] Screen is OFF
>
> 12-03 13:46:00.805  2334 27986 W MdnsClient: unicast receiver thread is
>> already dead.
>
> 12-03 13:46:00.855 23506 23506 I Obd_Connection:
>> AutoConnDeviceProviderImpl - Device Broadcast received:
>> android.intent.action.SCREEN_OFF
>
> 12-03 13:46:00.855 23506 23506 D Obd_Connection: AutoConnLogicImpl -
>> Device_onStateOff() (screen) is called
>
> 12-03 13:46:00.855 23506 23506 V Obd_Connection: AutoConnLogicImpl -
>> Caller (for 'Device_onStateOff') is notifying thread (1 requests in queue),
>> action: DEVICE_OFF
>
> 12-03 13:46:00.855 23506 23581 V Obd_Connection: AutoConnLogicImpl -
>> Thread (for 'WaitingBecause: suspended') is after wait for caller (0
>> requests in queue)
>
> 12-03 13:46:00.855 23506 23581 D Obd_Connection: AutoConnLogicImpl -
>> theThread() got action DEVICE_OFF, threadState false, obdState false,
>> bluetoothState false, hasMacAddress true
>
> 12-03 13:46:00.855 23506 23581 D Obd_Connection: AutoConnLogicImpl -
>> theThread() has no reason to run, waiting for further instructions
>
> 12-03 13:46:00.855 23506 23581 V Obd_Connection: AutoConnLogicImpl -
>> Thread (for 'WaitingBecause: suspended') is waiting for caller (0 requests
>> in queue)
>
> 12-03 13:46:02.674   786  1474 W PowerManagerService: Sandman
>> unresponsive, releasing suspend blocker
>
> 12-03 13:46:03.211   786  2663 I PowerManagerService: Waking up from sleep
>> (uid 1000)...
>
> 12-03 13:46:03.216   786  1474 I DisplayPowerController: Blocking screen
>> on until initial contents have been drawn.
>
> 12-03 13:46:03.240   786   786 V KeyguardServiceDelegate:
>> onStartedWakingUp()
>
> 12-03 13:46:03.246   786  2663 I QCOM PowerHAL: Got set_interactive hint
>
> 12-03 13:46:03.247   786  2663 D PowerManagerService-JNI: Excessive delay
>> in setInteractive(true) while turning screen on: 31ms
>
> 12-03 13:46:03.252   786  1474 V KeyguardServiceDelegate:
>> onScreenTurnedOn(showListener =
>> com.android.server.policy.PhoneWindowManager$2@e95d5b1)
>
> 12-03 13:46:03.258   786  1474 I qti_sensors_hal: TMG-3993 Ambient: batch
>>   4.00    inf
>
> 12-03 13:46:03.258   786  1474 I qti_sensors_hal: TMG-3993 Ambient:
>> activate=1
>
> 12-03 13:46:03.262   786  1469 I DisplayManagerService: Display device
>> changed state: "Built-in Screen", ON
>
> 12-03 13:46:03.262   244   244 D SurfaceFlinger: Set power mode=2, type=0
>> flinger=0xb69a4000
>
> 12-03 13:46:03.262   244   244 D qdhwcomposer: hwc_setPowerMode: Setting
>> mode 2 on display: 0
>
> 12-03 13:46:03.281   786  5524 V KeyguardServiceDelegate: **** SHOWN
>> CALLED ****
>
> 12-03 13:46:03.285  3453 31692 E BrcmNfcJni: nfaConnectionCallback:
>> unknown event ????
>
> 12-03 13:46:03.285  3453 31692 D BrcmNfcJni:
>> RoutingManager::nfaEeCallback: NFA_EE_SET_TECH_CFG_EVT; status=0x0
>
> 12-03 13:46:03.285  3453 31692 D BrcmNfcJni:
>> RoutingManager::nfaEeCallback: NFA_EE_SET_PROTO_CFG_EVT; status=0x0
>
> 12-03 13:46:03.286  3453  7188 D BrcmNfcJni: RoutingManager::commitRouting
>
> 12-03 13:46:03.286  3453 31692 D BrcmNfcJni:
>> RoutingManager::nfaEeCallback: NFA_EE_UPDATED_EVT
>
> 12-03 13:46:03.286  3453 31695 E NxpTml  : _i2c_write() errno : 5
>
> 12-03 13:46:03.286  3453 31695 E NxpTml  : PN54X - Error in I2C Write.....
>
> 12-03 13:46:03.286  3453 31697 E NxpHal  : write error status = 0x1ff
>
> 12-03 13:46:03.286  3453 31692 E NxpHal  : write_unlocked failed - PN54X
>> Maybe in Standby Mode - Retry
>
> 12-03 13:46:03.288  3453 31695 E NxpTml  : _i2c_write() errno : 5
>
> 12-03 13:46:03.288  3453 31695 E NxpTml  : PN54X - Error in I2C Write.....
>
> 12-03 13:46:03.288  3453 31697 E NxpHal  : write error status = 0x1ff
>
> 12-03 13:46:03.288  3453 31692 E NxpHal  : write_unlocked failed - PN54X
>> Maybe in Standby Mode - Retry
>
> 12-03 13:46:03.308  2334  6691 I CryptAuthSync: [DeviceStateSyncManager]
>> The server is in sync with current state. Nothing to do
>
> 12-03 13:46:03.318 17295 17295 D HomeBaseSDK:
>> ScreenStateAndBootCompletedReceiver android.intent.action.USER_PRESENT
>
> 12-03 13:46:03.334  5186  5186 W Binder_E: type=1400 audit(0.0:117074):
>> avc: denied { ioctl } for path="socket:[7420249]" dev="sockfs" ino=7420249
>> ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0
>> tclass=unix_stream_socket permissive=0
>
> 12-03 13:46:03.334  5186  5186 W Binder_E: type=1400 audit(0.0:117075):
>> avc: denied { ioctl } for path="socket:[7420249]" dev="sockfs" ino=7420249
>> ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0
>> tclass=unix_stream_socket permissive=0
>
> 12-03 13:46:03.350  3388  3388 I LatinIME: Starting input. Cursor position
>> = 5,5
>
> 12-03 13:46:03.354   786  2671 E native  : do suspend false
>
> 12-03 13:46:03.355   257   257 D audio_hw_primary: adev_set_parameters:
>> enter: screen_state=on
>
> 12-03 13:46:03.355   257   257 E voice   :
>> voice_extn_compress_voip_set_parameters: COMPRESS_VOIP_ENABLED is not
>> defined
>
> 12-03 13:46:03.355   257   257 E bt_a2dp_hw: adev_set_parameters: ERROR:
>> set param called even when stream out is null
>
> 12-03 13:46:03.370   786   812 I qti_sensors_hal: LIS3DH Accelerometer:
>> batch  15.00    inf
>
> 12-03 13:46:03.370   786   812 I qti_sensors_hal: LIS3DH Accelerometer:
>> activate=1
>
> 12-03 13:46:03.371   786  2671 D WifiConfigStore: No blacklist allowed
>> without epno enabled
>
> 12-03 13:46:03.372   786  1474 I DisplayPowerController: Unblocked screen
>> on after 157 ms
>
> 12-03 13:46:03.375   786  1474 V KeyguardServiceDelegate:
>> onScreenTurnedOn()
>
> 12-03 13:46:03.381  3453  4103 D NfcService: Discovery configuration
>> equal, not updating.
>
> 12-03 13:46:03.397  2334  2334 I DeviceScanner: [MDNS] Screen is ON
>
> 12-03 13:46:03.401  2334  2334 I DeviceScanner: [CastNearby] Screen is ON
>
> 12-03 13:46:03.439 23506 23506 I Obd_Connection:
>> AutoConnDeviceProviderImpl - Device Broadcast received:
>> android.intent.action.SCREEN_ON
>
> 12-03 13:46:03.439 23506 23506 D Obd_Connection: AutoConnLogicImpl -
>> Device_onStateOn() (screen) state is on
>
> 12-03 13:46:03.439 23506 23506 V Obd_Connection: AutoConnLogicImpl -
>> Caller (for 'Device_onStateOn') is notifying thread (1 requests in queue),
>> action: DEVICE_ON
>
> 12-03 13:46:03.439 23506 23581 V Obd_Connection: AutoConnLogicImpl -
>> Thread (for 'WaitingBecause: suspended') is after wait for caller (0
>> requests in queue)
>
> 12-03 13:46:03.439 23506 23581 D Obd_Connection: AutoConnLogicImpl -
>> theThread() got action DEVICE_ON, threadState false, obdState false,
>> bluetoothState false, hasMacAddress true
>
> 12-03 13:46:03.439 23506 23581 D Obd_Connection: AutoConnLogicImpl -
>> theThread() has no reason to run, waiting for further instructions
>
> 12-03 13:46:03.439 23506 23581 V Obd_Connection: AutoConnLogicImpl -
>> Thread (for 'WaitingBecause: suspended') is waiting for caller (0 requests
>> in queue)
>
> 12-03 13:46:03.466   786 16072 D NetlinkSocketObserver:
>> NeighborEvent{elapsedMs=414839887, 192.168.1.1, [60E3276C9604],
>> RTM_NEWNEIGH, NUD_REACHABLE}
>
> 12-03 13:46:03.477 19963  1450 E ctxmgr  :
>> [ProducerActiveIntervalImpl]addNewAppInterval: already
>> contained:appKey=bxa@bb9b632b,appInterval=bwy@41cae40,record=key=(com.google.android.googlequicksearchbox,
>> 10026, account#1574598813#,
>> com.google.android.apps.gsa.extradex.kato.GmsContextManagerClientHelper,
>> 6a179351-4cfc-4f16-a577-910fe64257a3), t=1480754885853, name=1,
>> lifetime=(2), production=null, retention=null, dispatch=(1),
>> consumer=(byw@de81240f-211278651)
>
> 12-03 13:46:03.534   244   244 D qdhwcomposer: hwc_setPowerMode: Done
>> setting mode 2 on display 0
>
> 12-03 13:46:03.534   244   381 I qdhwcomposer: handle_blank_event: dpy:0
>> panel power state: 1
>
> 12-03 13:46:03.535   786  2700 D SurfaceControl: Excessive delay in
>> setPowerMode(): 272ms
>
> 12-03 13:46:04.457  2334 27986 W MdnsClient_Cast: #acquireLock. Multicast
>> lock not held. Acquiring. Subtypes:"DCAC4134,D2CA5178"
>
> 12-03 13:46:05.185  6158  6229 I Bandwidth: WeatherRequest,26400,WIFI
>
> 12-03 13:46:05.210  6158  6229 E Performance: Metric
>> [WeatherForecastRequest - parseForecast] Value [1] (ms)
>
> 12-03 13:46:05.227  6158  6229 E Performance: Metric
>> [WeatherForecastRequest - parseForecast - database] Value [16] (ms)
>
> 12-03 13:46:05.255  6158  6229 W SyncManager: The last updated time millis
>> for woeid [20068966] was inserted with [1480765565213]
>
> 12-03 13:46:05.474  6158  6232 I Bandwidth: WeatherAlertRequest,39,WIFI
>
> 12-03 13:46:05.474  6158  6232 E Performance: Metric [WeatherAlertRequest
>> - doInBackground] Value [0] (ms)
>
> 12-03 13:46:06.080   786   796 I art     : Background partial concurrent
>> mark sweep GC freed 29457(2MB) AllocSpace objects, 2(40KB) LOS objects, 25%
>> free, 47MB/63MB, paused 2.057ms total 117.136ms
>
> 12-03 13:46:06.383   786  2673 D ConnectivityService: notifyType
>> CAP_CHANGED for NetworkAgentInfo [WIFI () - 120]
>
> 12-03 13:46:09.743  2078  6814 I Process : Sending signal. PID: 2078 SIG: 9
>
> 12-03 13:46:09.775   786  3518 I WindowState: WIN DEATH: Window{7a3b164 u0
>> com.ionicframework.myapp674332/com.ionicframework.myapp674332.MainActivity}
>
> 12-03 13:46:09.777   786  3517 D GraphicsStats: Buffer count: 14
>
> 12-03 13:46:09.806   786  3555 I ActivityManager: Process
>> com.ionicframework.myapp674332 (pid 2078) has died
>
> 12-03 13:46:09.806   786  3555 W ActivityManager: Force removing
>> ActivityRecord{ea058af u0 com.ionicframework.myapp674332/.MainActivity
>> t8228}: app died, no saved state
>
> 12-03 13:46:09.986   786   800 W InputMethodManagerService: Got
>> RemoteException sending setActive(false) notification to pid 2078 uid 10161
>
> 12-03 13:46:09.984   800   800 W Binder_1: type=1400 audit(0.0:117076):
>> avc: denied { ioctl } for path="socket:[27703]" dev="sockfs" ino=27703
>> ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0
>> tclass=unix_stream_socket permissive=0
>
> 12-03 13:46:09.984   800   800 W Binder_1: type=1400 audit(0.0:117077):
>> avc: denied { ioctl } for path="socket:[27703]" dev="sockfs" ino=27703
>> ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0
>> tclass=unix_stream_socket permissive=0
>
> 12-03 13:46:10.543  3542  3865 W OpenGLRenderer: Incorrectly called
>> buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
>
> 12-03 13:46:10.543  3542  3865 W OpenGLRenderer: Incorrectly called
>> buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
>
> 12-03 13:46:12.448   786  2673 D ConnectivityService: notifyType
>> CAP_CHANGED for NetworkAgentInfo [WIFI () - 120]
>
> 12-03 13:46:18.836   786 16072 D NetlinkSocketObserver:
>> NeighborEvent{elapsedMs=414855257, 192.168.1.1, [60E3276C9604],
>> RTM_NEWNEIGH, NUD_STALE}
>
> 12-03 13:46:23.855   786  2671 D WifiStateMachine: starting scan for
>> "joker"-WPA_PSK with 2437
>
> 12-03 13:46:24.396   786 16072 D NetlinkSocketObserver:
>> NeighborEvent{elapsedMs=414860817, 192.168.1.1, [60E3276C9604],
>> RTM_NEWNEIGH, NUD_REACHABLE}
>
> 12-03 13:46:28.416   786 16072 D NetlinkSocketObserver:
>> NeighborEvent{elapsedMs=414864837, 192.168.1.1, [60E3276C9604],
>> RTM_NEWNEIGH, NUD_STALE}
>
>

**Comment by dbaq** [comment]
This stacktrace shows that your app got killed by the activity manager probably because of some memory issue.

Have you tried a simple app to use this plugin?

> 12-03 13:46:06.080   786   796 I art     : Background partial concurrent
> mark sweep GC freed 29457(2MB) AllocSpace objects, 2(40KB) LOS objects, 25%
> free, 47MB/63MB, paused 2.057ms total 117.136ms
> 12-03 13:46:06.383   786  2673 D ConnectivityService: notifyType
> CAP_CHANGED for NetworkAgentInfo [WIFI () - 120]
> 12-03 13:46:09.743  2078  6814 I Process : Sending signal. PID: 2078 SIG: 9
> 12-03 13:46:09.775   786  3518 I WindowState: WIN DEATH: Window{7a3b164 u0
> com.ionicframework.myapp674332/com.ionicframework.myapp674332.MainActivity}
> 12-03 13:46:09.777   786  3517 D GraphicsStats: Buffer count: 14
> 12-03 13:46:09.806   786  3555 I ActivityManager: Process
> com.ionicframework.myapp674332 (pid 2078) has died
> 12-03 13:46:09.806   786  3555 W ActivityManager: Force removing
> ActivityRecord{ea058af u0 com.ionicframework.myapp674332/.MainActivity
> t8228}: app died, no saved state

**Comment by dbaq** [comment]
Closing this one, if it is still an issue, please reopen it.
