### ISSUE TITLE
ERROR: Method 'startWatch:' not defined in Plugin 'SMS'

### ISSUE THREAD

**Issue by chrisbenseler** [cordova-sms/cordova-sms-plugin#119]
This error appears in an Ionic 2 app, iOS (didn't test in Android).

ionic info:

> cordova: 6.3.1
> Ionic CLI Version: 2.1.13
> Ionic App Lib Version: 2.1.7
> ios-deploy version: 1.9.0 
> ios-sim version: 5.0.12 
> OS: OS X El Capitan
> Node Version: v6.9.1
> Xcode version: Xcode 8.1 Build version 8B62

Can anyone help me?

**Comment by dbaq** [comment]
are you sure you are not using cordova-plugin-sms. This plugin is a readonly one.
