### ISSUE TITLE
Emulator?

### ISSUE THREAD

**Issue by eholland7080** [cordova-sms/cordova-sms-plugin#121]
Hello, this is a great plugin.  Was wondering if it works running it on an emulator.  I'm sending the test SMS to itself via 5554, but it does not work.  Was wondering if this is because I'm running it on an Android emulator.
Thanks everyone
Eric

**Comment by dbaq** [comment]
hey @eholland7080, that's a good question, I never tried within an emulator.

Did you figure this out?

I am closing this one since it's been a few months. Feel free to reopen it if the issue still occurs.
