### ISSUE TITLE
hasPermission not defined error

### ISSUE THREAD

**Issue by gchokeen** [cordova-sms/cordova-sms-plugin#122]
Hi,

I am getting below error when try to use this plugin in the ionic 2.

**Error**

> Error: TypeError: Cannot read property 'hasPermission' of undefined

**Environment** 

> Cordova CLI: 6.4.0 
> Ionic Framework Version: 2.0.0-rc.0
> Ionic CLI Version: 2.1.7
> Ionic App Lib Version: 2.1.4
> Ionic App Scripts Version: 0.0.30
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Linux 3.13
> Node Version: v6.6.0
> Xcode version: Not installed

> Android ver: 6.0.1

As ionic 2 documented [here](https://ionicframework.com/docs/v2/native/sms/) I used the plugin as below
```

SMS.hasPermission((success)=>{
SMS.send();
},(error)=>{
});
```
  
Note: SMS.send works when I use outside hasPermission wrp

**Comment by dbaq** [comment]
hey @gchokeen,

have you figured this out?

**Comment by gchokeen** [comment]
Hi @dbaq ,

 I was not able to figure out why I got this error, but I remember I removed the hasPermission wrap and it worked.

```
SMS.send(mobNum, smsText ,{android:{intent: 'INTENT'}});
```

**Comment by lenichols** [comment]
+1

**Comment by dbaq** [comment]
on which device are you guys testing?

**Comment by gchokeen** [comment]
I used ```Android ver: 6.0.1``` MOTO G 4 plus device

**Comment by dbaq** [comment]
`hasPermission` has been added to ionic-native: https://github.com/ionic-team/ionic-native/blob/995fd56894234c9cdb0f9e873822d12313aa6e88/src/%40ionic-native/plugins/sms/index.ts#L68-L77
