### ISSUE TITLE
Chromium webview issue

### ISSUE THREAD

**Issue by Poola123** [cordova-sms/cordova-sms-plugin#123]
1: ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver
2: Cannot call determinedVisibility() - never saw a connection for the pid: 28468
I implemented the sms plugin and while im trying to run the app i got the above two errors in the logcat can anyone help me with the issue...Thankyou

**Comment by dbaq** [comment]
Hello @Poola123,

Can you please share some code, the cordova version and the platform you are using. 

Thanks.

**Comment by Poola123** [comment]
Hello @dbaq ,
Cordova version is 2.2.0 and the platform is Android.

code:index.html page
<!DOCTYPE HTML>	
	<html>
          <head>
              <meta charset="utf-8" />
              <meta name="format-detection" content="telephone=no" />
              
              <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height" />
              <link rel="stylesheet" type="text/css" href="css/index.css" />
              <title>Hello World</title>
          </head>
          <body>
              <div class="app">
                  <h1>Apache Cordova</h1>
                  <div id="load" class="blink">
                      
                     
                      <a href="sms.html">sms</a>
                      
                     
                  </div>
              </div>
              
              <script type="text/javascript" charset="utf-8″ src="cordova-2.2.0.js"></script>
              <script type="text/javascript" src="js/index.js"></script>
              <script type="text/javascript">
                  app.initialize();
              </script>
          </body>
	 </html>
when i run the app using eclipse ide i got those two errors.

Thanks.

**Comment by dbaq** [comment]
can you simply run the build via  `cordova build` and let me know?

**Comment by Poola123** [comment]
I have tried to run it using phonegap build and now i got this errors.
Error:1:Uncaught ReferenceError: require is not defined
    at sms.js:3
2: Uncaught TypeError: Cannot read property 'send' of undefined
    at Object.sendSms (sms.html:26)
    at HTMLInputElement.onclick (sms.html:35)
 sms.html code:

<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta name="format-detection" content="telephone=no" />
		<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height" />
		<script type="text/javascript" charset="utf-8″ src="cordova-2.2.0.js"></script>
		<script type="text/javascript" src="sms.js"></script>
		<script type="text/javascript">
			 var app = {
        sendSms: function() {
            var number = document.getElementById('numberTxt').value;
            var message = document.getElementById('messageTxt').value;
            console.log("number=" + number + ", message= " + message);
			alert("number=" + number + ", message= " + message);
            //CONFIGURATION
            var options = {
                replaceLineBreaks: false, // true to replace \n by a new line, false by default
                android: {
                    intent: 'INTENT'  // send SMS with the native android SMS messaging
                    //intent: '' // send SMS without open any other app
                }
            };

            var success = function () { alert('Message sent successfully'); };
            var error = function (e) { alert('Message Failed:' + e); };
            sms.send(number, message, options, success, error);
        }
		};

		</script>
</head>
<body>
	Mobile No:<input id="numberTxt" placeholder="Enter mobile number" value="" type="tel" /><br>
	Text box:<textarea id="messageTxt" placeholder="Enter message"></textarea></br>
	<input type="button" onclick="app.sendSms()" value="Send SMS" />
</body>
</html>

**Comment by dbaq** [comment]
hey @Poola123,

have you figured this out? it seems to me an exception due to an external application or code. If it is still an issue, please re-open it.
