### ISSUE TITLE
Get Callback of success or error from default app to my app using cordova-sms-plugin

### ISSUE THREAD

**Issue by inplamba** [cordova-sms/cordova-sms-plugin#124]
Hi All,Can anyone help me out
I need success or error callback from default App.
For example, if you press send then the app passes the data to the default SMS app, and if there is a network issue or for some reason the SMS does not get sent, the callback from default app will return as error callback to my app ,How could be it can be implemented .Thanks in Advance @dbaq

**Comment by dbaq** [comment]
hey @inplamba,

It is a restriction on android, please read https://github.com/cordova-sms/cordova-sms-plugin/issues/26.

Thanks
