### ISSUE TITLE
Default behavior when sending sms

### ISSUE THREAD

**Issue by mrlonnie** [cordova-sms/cordova-sms-plugin#127]
Is the default behavior(Android specifically) after sending the sms, to close the sms app or keep it open?  It appears to be working differently on different android phones.  And if the behavior is to keep the sms app open, is there a way to force close the sms app after sending?

**Comment by dbaq** [comment]
@pixelpuffpastry sorry for the delay, I haven't seen that issue. 

> Is the default behavior(Android specifically) after sending the sms, to close the sms app or keep it open?

After sending the SMS, the SMS app should be closed automatically. It depends on the SMS app developer. 

> It appears to be working differently on different android phones.

Is it the same SMS app on both phones?

>  is there a way to force close the sms app after sending?

no there is not unfortunately

**Comment by mrlonnie** [comment]
Thanks for the update!  
> Is it the same SMS app on both phones?

we are testing with the default messaging apps on two different phones (Samsung Galaxy S5 && Nexus 6P).  It closes on the 6P but stays open on the S5.

**Comment by dbaq** [comment]
Ok, that's interesting. What about the android version itself? is it the same on both devices? Can you share a simple .apk file so I can try on my google pixel?

**Comment by dbaq** [comment]
Closing this one since no answer. Feel free to reopen.
