### ISSUE TITLE
Not asking for permission and sending 'null' message

### ISSUE THREAD

**Issue by lionlancer** [cordova-sms/cordova-sms-plugin#128]
Device: Samsung Galaxy S7
Android OS version: Nougat (7.0)

Issue: 
I'm using your sample code although I altered it a bit.

```
checkSMSPermission: function(number, message, successCallback, errorCallback) {
	var success = function (hasPermission) { 
		if (hasPermission) {
			//sms.send(...);
					
			onsole.log("number=" + number + ", message= " + message);

			//CONFIGURATION
			var options = {
				replaceLineBreaks: true, // true to replace \n by a new line, false by default
				android: {
					//intent: 'INTENT'  // send SMS with the native android SMS messaging
					intent: '' // send SMS without open any other app
				}
			};

			if(!successCallback) successCallback = function () { alert('Message sent successfully'); };
			if(!errorCallback) errorCallback = function (e) { alert('Message Failed:' + e); };
					
			sms.send(number, message, options, successCallback, errorCallback);
					
		}else {
			alert('error?');
			// show a helpful message to explain why you need to require the permission to send a SMS
			// read http://developer.android.com/training/permissions/requesting.html#explain for more best practices
		}
	};
			
	var error = function (e) { 
		alert('Something went wrong:' + e); 
	};
			
	sms.hasPermission(success, error);
			
}
```

After I called that script, it doesn't asks for permission but instead it alerts "error?". To get around with this, I just manually set up the permission in my device's settings. After that, it can successfully send SMS but there is another problem, the message it sent is "null" (without quotes) even though the console logs the correct number and the message. As you can see, I set the 'intent' to blank because I want the app to send SMS directly without opening any app. If I set the intent, it will show android native SMS app and it is pre-filled with the message I intend to send. Can you please fix the problem? I really appreciate the effort you've put into building this plugin. It also help other coders out there in case they encounter the same issue as mine.

Thanks a lot! :)

**Comment by dbaq** [comment]
hey @lionlancer, can you run `adb logcat` to check if you have a stacktrace in the logs?

**Comment by lionlancer** [comment]
Thanks for replying @dbaq. :)

I'm sorry, I'm not using any framework to build my app. I'm just writing everything manually. And I build it using PhoneGap Build. And I'm using my company's computer so I can't just download anything. Maybe I'll try testing at home during the weekend if I've got time. Is there any other thing I can do to help you fix this issue?

**Comment by dbaq** [comment]
The fact that you are using phonegap build could be the source of the issue. Once you have the .APK file generated, you can install it on your phone correct? Once it is running on your phone, you can plug your phone in your laptop via a usb cable and run `adb logcat` from a terminal to see all the logs of your phones (and potential exceptions).

**Comment by dbaq** [comment]
hello @lionlancer, any updates on this one?

**Comment by dbaq** [comment]
Closing this one since no answer. Please open a new issue if you still encounter problems.
