### ISSUE TITLE
Message cancelled on IOS

### ISSUE THREAD

**Issue by vegetablesalad** [cordova-sms/cordova-sms-plugin#129]
I get "Message cancelled" error every time. I can see that something flashes on the screen, but no message dialog shows up. Anyone else experiencing this ? My build SDK is 10.2

**Comment by dbaq** [comment]
hello @vegetablesalad,

can you check in xcode if you see a stack trace?

**Comment by vegetablesalad** [comment]
That's the worst thing, there is no errors. I traced it till the end and everything seems to work, except message is canceled at the end. If I delete everything inside "messageComposeViewController", then I get stuck at black screen.

**Comment by vegetablesalad** [comment]
So it seems to work on **5s iOS 9.0** but not on **5s iOS 10.2.1**
Probably iOS 10 fault

**Comment by dbaq** [comment]
thanks @vegetablesalad for digging into this issue. Can you try on different iOS version? 10.3 for instance?

**Comment by dbaq** [comment]
hello @vegetablesalad any updates on this one?

**Comment by vegetablesalad** [comment]
@dbaq so I got other phones with different iOS versions and it worked on all of them. Then I tried it on  **10.2.1** again and it WORKED. Code didn't have any changes, I deliberately kept it on different branch. So I don't know what to tell you, it could be something specific for my computer or code, OR some very elusive bug. Either way I don't have any more info on this
