### ISSUE TITLE
Pass an options object instead of passing a specific string for the android intent

### ISSUE THREAD

**Issue by dbaq** [cordova-sms/cordova-sms-plugin#13]
So far, the third parameter is a string specific for the android platform ('intent' or ''), it should be replaced by an option object containing (future) global configuration and platform specific configuration. It should also be backward compatible with the current version (i.e. if somebody passes a string instead of an object it must work)

here is a suggestion for the structure of the options:

```
{
    globalConf: true,
    globalConf2: false,
    android: {
        intent: '', //or 'INTENT'
        androidConf: true,
    },
    ios: {
        iosConf: false
    },
    wp8: {
        wp8Conf: false
    }
}
```

if nothing is passed, we will use default values.

**Comment by agarrharr** [comment]
What would globalConf2 be?

**Comment by dbaq** [comment]
for instance, in order to fix #6, we need to replace `\n` by a newline, but it should be configurable. Some users might not want to have the auto replace or want to replace another sequence of characters. Also with an options object, it will be better for future features (i.e. reading SMS).

What do you think?

**Comment by dbaq** [comment]
Also with a specific platform configuration will avoid some misunderstanding about the intent parameter. There are some users asking about this parameter on other forums.

**Comment by agarrharr** [comment]
Oh ok, so it would be something like this, and you could add more options as necessary. That sounds good. I would also add a `console.warn` message if they pass in a string as the third parameter saying that it's deprecated.

```
{
    multiLine: true,
    android: {
        intent: '', 
    }
}
```

**Comment by dbaq** [comment]
Yep exactly, will do that this week.

**Comment by dbaq** [comment]
Done via 47e1eb2.
