### ISSUE TITLE
Adding BroadcastReceiver in Android for subscribing to sms messages

### ISSUE THREAD

**Issue by vegetablesalad** [cordova-sms/cordova-sms-plugin#130]
Last week I had need for a BroadcastReceiver in android for processing incoming SMS messages. If you guys think this would be something useful in this plugin then I could try to contribute my code.

**Comment by dbaq** [comment]
hey @vegetablesalad,

Thanks for the suggestion. However, this plugin is a "send-only" plugin, we are trying to keep it simple. Other plugins are doing both sending and receiving SMS messages.
