### ISSUE TITLE
message delivered after too long

### ISSUE THREAD

**Issue by mbaaro** [cordova-sms/cordova-sms-plugin#131]
Hello thanks for this awesome piece. it is working perfectly for me when sending only one sms. I am however facing difficulties when i want to send two different messages to two different numbers simultaneously. I am getting the numbers from a formbuilder form and when i hit the send button, sometimes the two messages are delivered immediately while in other instances only one message is delivered while the other takes up to 30 minutes to be delivered or not delivered at all, meaning only one is sent.
It is however very important that the two messages are delivered.
i am calling the sms.send() functions one after the other as below

sms.send(sendernumber, 'your packages has been sent to '+recipientnumber);
sms.send(recipientnumber,  sendernumber+'has sent you a package');

i would appreciate any help from this forum.I am testing my application in deployment mode

**Comment by dbaq** [comment]
hey @mbaaro,

Sorry for the delay, I was on vacation. That's the first time I am reading about delays. I would say that it could come from your provider but that's unlikely. 

-In which country are you? 
-Which platform are you using? (iOS/android)
-What's the average delay before delivery?
-Have you checked the console in xcode (iOS)/logcat(android)?
-Can you try with another phone or another carrier?

**Comment by mbaaro** [comment]
-In which country are you?
-Which platform are you using? (iOS/android)
-What's the average delay before delivery?
-Have you checked the console in xcode (iOS)/logcat(android)?
-Can you try with another phone or another carrier?

Hello I am in Kenya and currently using Android.... The average delay is 20
minutes and no warnings or errors in my console

**Comment by dbaq** [comment]
This is probably due to your carrier. Please feel free to reopen the issue if it still happening to you.

**Comment by mbaaro** [comment]
Thank you....... improved a great deal by building my app in production mode
