### ISSUE TITLE
SMS won't be send on iOS 10

### ISSUE THREAD

**Issue by lanceadvanced** [cordova-sms/cordova-sms-plugin#135]
Hi everyone :)

I tried implementing the cordova-sms-plugin in my PhoneGap App. The installation was succesful, using the sample code does NOT throw an error regarding sms being undefined. Infact, a console.log of sms does show me the object specified in the www/sms.js file from the folder structure of the plugin.

However, when trying to execute sms.send() i get two different situations:
1. In Browser: I get an alert with the message "Message Failed:Missing Command Error". This happens due to  the function that serves as an error param in the send() call. In the console i get a log stating: 
"Error: exec proxy not found for :: Sms :: send".
Edit: The exec proxy is caused beacause the plugin does (abviously) not support browsers. 

2. On iPhone (iOS 10): Nothing happens. I get no alerts or crashes, however when trying to place an alert() after the send() call, the alert isnt executed. When placing the alert() before the send() call, it is executed. So I think the send call causes an error.

I've already read a bit into this error and couldn't find something helpful. I noticed that including the plugin via the config.xml file in the phonegap project might cause a problem. But as the sms object exists, this seems unimportant for this issue.
However, this is my entry for the cordova-sms-plugin in the config.xml:
 <plugin name="cordova-sms-plugin" spec="~0.1.11" />

I've included my source code in the attachement (Init.txt). 

I'd be glad for any help on this :)

Sincerly

François
[Init.txt](https://github.com/cordova-sms/cordova-sms-plugin/files/1111481/Init.txt)

**Comment by lanceadvanced** [comment]
Update: I figured out that in Browser, the Plugin is enabled and the sms.js is in the header, however on iOS and Android it isn't. I found it out when using Weinre to remote debug the Phonegap Developer Application.

**Comment by dbaq** [comment]
hey @lanceadvanced,

were you able to figure out your issue?

**Comment by lanceadvanced** [comment]
Hi, thanks for your reply :)
Unfortunately I didn't. I still get the message, that sms doesn't exists (in Debug, using weinre). The weird thing is, that in browser i get a message, that it couldn't find the exec proxy for the sms utility...
Is it possible to add the plugin in a wrong way for ios/andoird but in a right way for the browser?

**Comment by dbaq** [comment]
@lanceadvanced it is normal that it does not work in a browser. That's why you have the exec error.

is window.sms available?

**Comment by SpencerHehl** [comment]
Hi there, having the same issue here with iOS 11.  i run the sms.hasPermission and nothing happens. no error, no alert, nothing. I am wondering if there is something that needs to happen to explicitly give permissions first? there is never the pop up asking to give my app permissions to SMS like most other plugins. Also wondering if it needs something in the info.plist like a lot of other plugins are having to do since iOS 10?

**Comment by lanceadvanced** [comment]
Hi dbaq :) In an iOS App (launched through Xcode) and using the Safari remote Debugging, I get an error, that window.sms is undefined. I mentioned the browser, because in browser, windows.sms is not undefined. I just get an exec proxy error (which is fine as a browser cant send sms). 
So this is the current state both on iOS 10 and 11.

**Comment by dbaq** [comment]
hey @lanceadvanced, please check this out https://github.com/cordova-sms/cordova-sms-plugin#sms-is-undefined

**Comment by dbaq** [comment]
@lanceadvanced  have you figured this out?
