### ISSUE TITLE
Android App Crashes when default App changes and opened with this plugin

### ISSUE THREAD

**Issue by princeJio** [cordova-sms/cordova-sms-plugin#136]
@dbaq  I changed my default messaging app to new messaging app from my nexus phone then I open my app and send sms using cordova-sms-plugin with intent:"INTENT" but my app crashes every time when I click on send button and unable to route my messaging app. 

ADB LOGS AFTER CRASH

07-14 10:15:11.773   249   264 I Ext4Crypt: No master key, so not ext4enc
07-14 10:15:12.056   860  3246 I chatty  : uid=1000(system) Binder_B expire 2 lines
--------- beginning of crash
07-14 10:15:12.497  4649  4649 E AndroidRuntime: FATAL EXCEPTION: main
07-14 10:15:12.497  4649  4649 E AndroidRuntime: Process: com.harman.obd, PID: 4649
07-14 10:15:12.497  4649  4649 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.harman.obd.OBDService@8394b92 with Intent { cmp=com.harman.obd/.OBDService }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at android.app.ActivityThread.-wrap17(ActivityThread.java)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-14 10:15:12.497  4649  4649 E AndroidRuntime: **Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null objec**t reference
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at com.harman.obd.OBDService.onStart(OBDService.java:94)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at android.app.Service.onStartCommand(Service.java:459)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
07-14 10:15:12.497  4649  4649 E AndroidRuntime:        ... 8 more
07-14 10:15:14.497   860   871 I chatty  : uid=1000(system) Binder_2 expire 4 lines
07-14 10:15:14.519   860   878 I chatty  : uid=1000(system) android.display expire 1 line
07-14 10:15:15.169   860  1342 I chatty  : uid=1000(system) WifiService expire 1 line
07-14 10:15:15.815   860  4089 I chatty  : uid=1000(system) Binder_F expire 2 lines
07-14 10:15:17.379   860  1404 I chatty  : uid=1000(system) Binder_3 expire 10 lines
07-14 10:15:19.172  4914  4914 E AndroidRuntime: **FATAL EXCEPTION**: main
07-14 10:15:19.172  4914  4914 E AndroidRuntime: Process: com.harman.obd, PID: 4914
07-14 10:15:19.172  4914  4914 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.harman.obd.OBDService@8394b92 with Intent { cmp=com.harman.obd/.OBDService }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at android.app.ActivityThread.-wrap17(ActivityThread.java)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-14 10:15:19.172  4914  4914 E AndroidRuntime: **Caused by: java.lang.NullPointerException:** Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at com.harman.obd.OBDService.onStart(OBDService.java:94)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at android.app.Service.onStartCommand(Service.java:459)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
07-14 10:15:19.172  4914  4914 E AndroidRuntime:        ... 8 more
07-14 10:15:20.707   860  3830 I chatty  : uid=1000(system) Binder_C expire 11 lines

**Comment by andreszs** [comment]
Why would anyone want to use a custom app for sending SMS?

I noticed that on newer (and worser) Android versions now you are offered to use _Hangouts_ to send SMS, a total nonsense option, you should definitely avoid it and always use the native SMS app only.

**Comment by agarrharr** [comment]
@andreszs One reason you may want to use another app is you may want to use an open source app, or you may want to have [end to end encryption](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=en). Or you may want to be able to send sms from your computer, which you can do with Hangouts when you have Google Fi. Or other apps, may have other features that you want.

**Comment by dbaq** [comment]
Closing this one since no answer. Please open a new issue if you still encounter problems.
