### ISSUE TITLE
Cannot send on KitKat 

### ISSUE THREAD

**Issue by gonzalovinas** [cordova-sms/cordova-sms-plugin#138]
Sms.java, at line 113 defines checkSupport method, which is only used when invoking the send functionality. On KitKat it always return false. Higher versions return true and works ok.

private boolean checkSupport() {
		Activity ctx = this.cordova.getActivity();
		return ctx.getPackageManager().hasSystemFeature(PackageManager.FEATURE_TELEPHONY);
	}

**Comment by dbaq** [comment]
hey @gonzalovinas,

Quite weird since `FEATURE_TELEPHONY` has been around since android 2.1 (https://developer.android.com/reference/android/content/pm/PackageManager.html#FEATURE_TELEPHONY)

Have you tried on different phones?

**Comment by gonzalovinas** [comment]
I mean KitKat emulator... does it change the scenario in anyway?

**Comment by dbaq** [comment]
Sorry I didn't see your answer. Yes, the emulators are quite old and don't always simulate the telephony feature. You need to test on real devices.
