### ISSUE TITLE
iOS send sms with less than 5 characters make the send box disapear

### ISSUE THREAD

**Issue by fatalcaron** [cordova-sms/cordova-sms-plugin#142]
I send sms to communicate with some devices. On iOS the message that contains less than 5 characters, the send box disappears and I have to click on the phone number entry so that it reappears.

**Comment by dbaq** [comment]
hey @fatalcaron is it always happening if the message is less than 4 characters? could it be related to #22?

**Comment by fatalcaron** [comment]
Not really sure now. I don't understand why it's happening, all my sms functions is in a shared service to all my components and this bug only occur in one page of my app. The page where I sent short message, less than 5 characters. Yes it's related to 22!

**Comment by dbaq** [comment]
ok so closing this one since it is related to #22.
