### ISSUE TITLE
Avoid "Open with" dialog on Android 7

### ISSUE THREAD

**Issue by andreszs** [cordova-sms/cordova-sms-plugin#144]
On Android 7.1.1, why am I prompted to select an app to **open with** for sending SMS? Of course we must use Messenger and only Messenger for SMS, why are we offered to use Hangouts which cannot send SMS to begin with? If there's some way to avoid this idiotic behavior, please let me know. Thanks.

![sms](https://user-images.githubusercontent.com/10298071/30381675-739a1970-9873-11e7-9463-1ca605a219ba.png)

**Comment by agarrharr** [comment]
On Android you have a choice about which app you want to use to send sms. Android uses "Intents" to allow different apps to handle types of activities. So, for example, when tap "share" inside an app, other apps say that they can handle the share intent. In this case, Messenger and Hangouts, say that they can handle the sms intent.

I'm not exactly sure why Hangouts is saying it can handle the sms intent if you can't send sms with Hangouts, but some people can. For instance, if you use Google Fi, then you can use Hangouts as your default sms app.

You can choose if you want to open up another app to send the sms, or just send it without opening another app with the intent option.

```js
// CONFIGURATION
var options = {
  replaceLineBreaks: false, // true to replace \n by a new line, false by default
  android: {
    intent: 'INTENT'  // send SMS with the native android SMS messaging
    // intent: '' // send SMS without open any other app
  }
};
```

**Comment by agarrharr** [comment]
Actually, the reason it's showing Hangouts may be because you are on an emulator.

**Comment by agarrharr** [comment]
And I think, if you tried it on your phone, and you only have Messenger installed, and you don't or can't use Hangouts for sms, then you won't even see this option pop up.

**Comment by dbaq** [comment]
Thanks @agarrharr for answering this one. Closing it since the question has been answered. Cheers.
