### ISSUE TITLE
Won't send an sms from android device. Browser's console shows sms is not defined.

### ISSUE THREAD

**Issue by muli-cohen** [cordova-sms/cordova-sms-plugin#145]
Hi, Thanks for this great plugin, but I also got this issue. I installed the plugin via both cli and phonegap, but when I try to send an sms with my device nothing happens. The intersting thing is, that during installation of the apk, I get a notion that the app has access to "send SMS messages - this may cost you money". Also this plugin is showing on the phongap build plugin section. What am I doing wrong?
I'm very new to PhoneGap\Cordova.

Thanks again,

Samuel.

**Comment by dbaq** [comment]
hey @mulic3,
You should try in an emulator to see if the sms composer opens or not. Have you tried on different devices?

**Comment by dbaq** [comment]
Closing this one since no answer. Please open a new issue if you still encounter problems.
