### ISSUE TITLE
How to send SMS without saving the sms text 

### ISSUE THREAD

**Issue by deryfebriantara** [cordova-sms/cordova-sms-plugin#152]
HI..
I build an app that send sms with Token text to the receiver number,
but I don't want the sender  know the token that sent to the receiver. 
is that possible to use this plugin?
I try this plugin but the text that I send saved in conversation phone sms dialog. 
thanks in advance..

**Comment by dbaq** [comment]
hello @deryfebriantara,

It is not possible to achieve what you want with this plugin. We are sending a text message as the current user. If you want to send some kind of token that you don't want your current user to see, you need to send a text message from your server. You should check out Twilio in that case.
