### ISSUE TITLE
The message won't sent If the message contain number (0-9)

### ISSUE THREAD

**Issue by wish4129** [cordova-sms/cordova-sms-plugin#154]
I'm unable to send out the SMS whenever the message contain number (0-9).
I've tried for few times. Any clue for me?

Android 5.01
LG G PRO 2 (D838)

ionic version 3.19.0
cordova version 7.1.0

**Comment by dbaq** [comment]
Hey @wish4129,

This sounds fairly surprising. Is it happening only on a specific device?

**Comment by I-Dont-Remember** [comment]
It's possible I know the answer @wish4129. After hours and hours of trying to find this issue, my partner and I found that to send a message we had to preface the number with `n`, so `n1234564444`, otherwise the app would crash.  Hopefully it's the same issue you ran into.
