### ISSUE TITLE
intent not working

### ISSUE THREAD

**Issue by mcamendoza1** [cordova-sms/cordova-sms-plugin#155]
Intent : '' is not working, i'm using ionic framework. 
it still uses Android Messaging (Default SMS App).

```      
let options: {
    replaceLineBreaks: false,
    android: {
     //intent: 'INTENT' // send SMS with the native android SMS messaging
     intent: '' // send SMS without open any other app
    }
}

if(this.sms.hasPermission){
      this.sms.send(number,'Hello Woof!', options).then((res) => {
        console.log(res);
        alert('Messange Sent!')
      }).catch((err) =>{
        alert(JSON.stringify(err));
      })
}
 ```

**Comment by dbaq** [comment]
hello @mamendoza1,

have you figured this out? Sending a SMS without intent on android works well. Which version of android are you trying on? which version of ionic? can you please share some a repo?

**Comment by dbaq** [comment]
Closing this one due to no reply.

**Comment by krishnarout** [comment]
> hello @mamendoza1,
> 
> have you figured this out? Sending a SMS without intent on android works well. Which version of android are you trying on? which version of ionic? can you please share some a repo?

hi, please tell  me how to send sms with intent:" " ,If  I am using  intent:" " then its showing me this error: **Unhandled** Promise rejection: User has denied permission ; Zone: <root> ; Task: null ; Value: User has denied permission undefined** please please tell me how to solve this error and able to send sms without opening the default messaging app please. I am checking with android 7.0 version.

**Comment by krishnarout** [comment]
> > hello @mamendoza1,
> > have you figured this out? Sending a SMS without intent on android works well. Which version of android are you trying on? which version of ionic? can you please share some a repo?
> 
> hi, please tell me how to send sms with intent:" " ,If I am using intent:" " then its showing me this error: **Unhandled** Promise rejection: User has denied permission ; Zone: ; Task: null ; Value: User has denied permission undefined** please please tell me how to solve this error and able to send sms without opening the default messaging app please. I am checking with android 7.0 version.

I am using ionic version 4  with "cordova-android":7.1.1
please tell me the solution I am trying this one for few days its important for me please reply me
