### ISSUE TITLE
Unable to Install Plugin

### ISSUE THREAD

**Issue by singhiam** [cordova-sms/cordova-sms-plugin#156]
Hi, 

Thanks for this Plugin but I am having issues while installation in Ionic 2 Project.

npm install --save @ionic-native/sms
npm ERR! Unexpected token < in JSON at position 149

**Comment by dbaq** [comment]
hello @singhiam 

I am closing this issue since it has been a few weeks. You should follow that page: https://ionicframework.com/docs/native/sms/

If it is still not working, you should contact the ionic dev. They coded the wrapper, I have no access to that code.
