### ISSUE TITLE
"Platform not supported" on Android 6.0.1 (Lenovo Tab2 A10-30).

### ISSUE THREAD

**Issue by muli-cohen** [cordova-sms/cordova-sms-plugin#157]
So I got this same error when the tablet was on 5.1, so I updated to 6 hoping it will solve the problem, but I still get "Platform not supported". The same code works flawlessly on Android Nougat on a different device. What could be the problem?
This is my code:
```
 var app = {
    sendSms: function() {

          var options = {
            replaceLineBreaks: false, // true to replace \n by a new line, false by default
            android: {
                intent: ''  // send SMS with the native android SMS messaging
                //intent: '' // send SMS without open any other app
            }
        };
        sms.send(thisalt.split(" ").pop(), "check check", options);
    }
};
```
Thanks a lot for all your hard work, it is greatly appreciated!

**Comment by dbaq** [comment]
Hey @mulic3,

Here is what I do to check if your device can send SMS.

https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/android/Sms.java#L119-L122

Are you sure this tablet as the `FEATURE_TELEPHONY`?

Cheers,

**Comment by muli-cohen** [comment]
Thanks again for you time!
Yes, I am able to make phone calls and send SMS with this tablet, it fully supports it.
Could it be because I left the checkSMSPermission method out of my code?

**Comment by dbaq** [comment]
if you remove this method, does it work? also, in your android manifest file do you have the `android.Manifest.permission.SEND_SMS` permission?

**Comment by muli-cohen** [comment]
Thanks. I got the `android.Manifest.permission.SEND_SMS` permission. Also, it works on a nougat device flawlessly. I already got the `checkSMSPermission ` method out of my code, should I try to add it in? I would try in a heartbeat but not so sure I implement it right in my code:
```
    var app = {
        sendSms: function() {
    
       var success = function (hasPermission) { 
                if (hasPermission) {
            sms.send(thisalt.split(" ").pop(), "check check", options);
                }
                else {
                    alert("bla bla");
                }
            };
            var error = function (e) { alert('Something went wrong:' + e); };
            sms.hasPermission(success, error);
        }
             
            };
            var options = {
                replaceLineBreaks: false, // true to replace \n by a new line, false by default
                android: {
                    intent: ''  // send SMS with the native android SMS messaging
                    //intent: '' // send SMS without open any other app
                
        }
    };
```
Maybe all the problem is because the device came with 5.1, even though I installed an OTA 6.0.1 update?
Should it support android 5.1?
Thanks again for your precious time.

**Comment by muli-cohen** [comment]
Just to update, the code above gives me an 'Message send successfully' alert but doesn't really send anything. Is there something wrong in my code?

**Comment by dbaq** [comment]
hey @mulic3, have you found a solution? tried on other devices?

**Comment by muli-cohen** [comment]
@dbaq Thanks for your response. After the hasPermission it alerts that the message was sent successfuly but it doesn't send anything. As I mentioned before, this is on a Lenovo Tab2 A10-30 with android 6.0 installed (came stock with Lollipop). I works fine on a different device with android 7. Any idea?

**Comment by dbaq** [comment]
I don't have a lenovo tablet, so it is really difficult for me to help you out. Can you check the logcat logs (`$ adb logcat`) and see if you have any errror?

**Comment by dbaq** [comment]
Closing this as no answer, please free to reopen it.
