### ISSUE TITLE
Cannot link cordova function for SMS

### ISSUE THREAD

**Issue by forestlance** [cordova-sms/cordova-sms-plugin#158]
I am having a problem getting my Basic app code to include a cordova plugin for sending (outgoing) SMS.  This is the first mobile app I have built, and I have been around the NSbasic and github cordova sites looking for help.  It seems no matter what I do, I am having a problem seeing the function either at compiling or runtime.

My config.xml right now, which after trial and error I think may be right:
<plugin name="cordova-sms-plugin" source="npm" />

My form code:
  Dim options = {}
  options.replaceLineBreaks = False  'True To Replace \n by a new line, False by default
  options.android = {}
  options.android.intent = "INTENT"
  sms.sendSMS(inpNumber.value, txtMessage.value, options, success, error);

This finally compiles in the NSbasic ide without any errors.  When I ask it to create a native app with PhoneGap, it is successful building then runs, but at the point it would call the function it says:
Uncaught TypeError: sms.sendSMS is not a function.

**Comment by dbaq** [comment]
Hey @forestlance,

`sendSMS`? you are not using this plugin but probably another one like https://github.com/floatinghotpot/cordova-plugin-sms. Double check the plugin name in your config file.

This plugin is a "send only" plugin. The function is `sms.send`, you can find more details in the README.md.

Cheers,
