### ISSUE TITLE
Trying to send a SMS to a contact with who there is one sms unsent - Black screen (IOS only)

### ISSUE THREAD

**Issue by smiileTeam** [cordova-sms/cordova-sms-plugin#159]
Hi,

I have an issue with the plugin when i try to send an sms on IOS (version ios 11.2.1).

if  i try to send a sms to a number with which i already tryed to send a sms who failed cause of network or icloud account unconfigured

To reproduce this :

Try to send an sms to a number without sim card or anything to fail the sms send.
In app try to send a sms with the plugin to this same number, when the plugin try to open the sms composer of the mobile, he get stuck on black screen.

If i delete this sms unsent or if i send it with success and go back in app : the plugin work as expected. 

Thank you.

**Comment by dbaq** [comment]
Hey @smiileTeam,

Thanks for the report, that's an interesting issue. Is there any stacktrace in xcode that you can share?

Thanks

**Comment by smiileTeam** [comment]
Hi @dbaq 

The only trace i can see in xcode when i trigger this issue is : "[App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction”.

I could test on ipad with ios 10.3.2, there is no this issue

Thanks

**Comment by dbaq** [comment]
Maybe something is missing in the error handler the first time.

Side question: can you confirm that you are using `cordova-sms-plugin` and not a fork or `sms-cordova-plugin` repo?

**Comment by smiileTeam** [comment]
here the line in my package.json :  
"cordova-sms-plugin": "^0.1.11",

i use it with the wrapper of ionic "@ionic-native/sms": "^4.5.2",

**Comment by pedroampuc** [comment]
I have the same issue:
<plugin name="cordova-sms-plugin" spec="^0.1.11" /> 
ionic wrapper: "@ionic-native/sms": "^4.5.2",

cli packages:

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.8 
    Node       : v8.6.0
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

**Comment by dbaq** [comment]
@pedroampuc thanks for the report, any stacktrace in xcode for you? would love some help to debug this issue. I don't have much free time currently.

**Comment by hardikrawal23** [comment]
Yes even I am getting the same error on Ionic v3. Following is the log from Xcode :

Main Thread Checker: UI API called on a background thread: -[UIAlertView initWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:]
PID: 36989, TID: 939602, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   NariShakti App                      0x0000000103a75d4c __12-[Sms send:]_block_invoke + 284
5   libdispatch.dylib                   0x000000010d25f2f7 _dispatch_call_block_and_release + 12
6   libdispatch.dylib                   0x000000010d26033d _dispatch_client_callout + 8
7   libdispatch.dylib                   0x000000010d265251 _dispatch_queue_override_invoke + 1458
8   libdispatch.dylib                   0x000000010d26c102 _dispatch_root_queue_drain + 772
9   libdispatch.dylib                   0x000000010d26bda0 _dispatch_worker_thread3 + 132
10  libsystem_pthread.dylib             0x000000010d7275a2 _pthread_wqthread + 1299
11  libsystem_pthread.dylib             0x000000010d72707d start_wqthread + 13
2018-02-27 01:22:35.038405+0530 NariShakti App[36989:939602] [reports] Main Thread Checker: UI API called on a background thread: -[UIAlertView initWithTitle:message:delegate:cancelButtonTitle:otherButtonTitles:]


Request urgent help

**Comment by prosenjit-itobuz** [comment]
I got the solution from here: https://stackoverflow.com/questions/38458170/ios-10-app-if-were-in-the-real-pre-commit-handler-we-cant-actually-add-any

**Comment by prosenjit-manna** [comment]
Just uninstall the app from device and install!

**Comment by prosenjit-manna** [comment]
Sometimes uninstall works, Sometimes not!

**Comment by hohae** [comment]
Any news on that topic? Any more ideas how to solve it?

**Comment by dbaq** [comment]
hey @hohae, I can't find an explanation for that yet. I was not able to reproduce, I am trying to get another iphone to reproduce the issue. Can you make sure the phone number variable you send is a string? That's the only explanation I can find online.

**Comment by hohae** [comment]
Hi Didier,

I had a chance to reproduce it sometimes with iOS 11.4.1 on my iPhone 7. Behaviour seems to be as follows:
Normally you get back a MessageComposeResultSent, when you put a SMS message into the queue. If you are fast enough to put another one into the queue before the toast flies in that the message could not be sent, you get a black screen in most cases. This lasts about 1 minute and then returns with a MessageComposeResultCancelled.

Hopefully this leads you into the right direction.

Regards,
Holger

**Comment by hohae** [comment]
Hi,

according to our tests, this issue disappeared with iOS 12.0.1

Cheers,
Holger

**Comment by dbaq** [comment]
Thanks for the update, I am closing this since iOS 12 adoption is already over 50%.
