### ISSUE TITLE
Need to know sender phone no after success

### ISSUE THREAD

**Issue by amirul1000** [cordova-sms/cordova-sms-plugin#161]
I need to verify the phone no.after success I need to track the sender phone no
How may I get this no

 if(SMS) SMS.sendSMS("Receiver phone no", msg , function(){
            //success
           ///What is sender phone no?

},function()
{
   //error
});

**Comment by dbaq** [comment]
hello @amirul1000, this plugin only sends SMS to a recipient. We do not need to retrieve the sender's phone number. You might want to look at this plugin: https://github.com/pbakondy/cordova-plugin-sim

Cheers
