### ISSUE TITLE
Compiling cordova-sms-plugin triggers malware security alert from Avira

### ISSUE THREAD

**Issue by mc-sm** [cordova-sms/cordova-sms-plugin#164]
When running "cordova run android" on my development pc, its Avira antivirus software displayed the following security alert along with the below compiler failure:

> 'C:\...\Sms.dex' containing the pattern of 'ANDROID/TrojanSMS.Agent.FV.Gen' was blocked. We moved the file to quarantine.

> :app:transformClassesWithDexBuilderForDebug FAILED
> What went wrong:
> Failed to capture snapshot of output files for task 'transformClassesWithDexBuilderForDebug' property 'streamOutputFolder' during up-to-date check.
> Failed to create MD5 hash for file 'C:\...\platforms\android\app\build\intermediates\transforms\dexBuilder\debug\0\com\cordova\plugins\sms\Sms.dex'.

Avira's description of the malware is at https://www.avira.com/en/support-threats-summary-product/tid/8947/threat/Android.TrojanSMS.Agent.BVL.Gen.

A search turned up no instances of cordova-sms-plugin being associated with malware.

Any help on how to get past this error is appreciated.  Thanks!

**Comment by dbaq** [comment]
Hey @mc-sm, thanks for reporting this issue. Have you tried with another antivirus? The code is fully open source, you can see by yourself that there is no malware in this plugin

**Comment by mc-sm** [comment]
Thanks @dbaq. I created exceptions for the following three files in Avira Antivirus:

1. Sms.dex
2. Sms_e47ad742.dex
3. Sms_eeed9533.dex

I'm now able to successfully build the app by running `cordova run android` at the CLI.
