### ISSUE TITLE
Plugin code obtained by running "cordova plugin add cordova-sms-plugin" omits some code contained on GitHub

### ISSUE THREAD

**Issue by mc-sm** [cordova-sms/cordova-sms-plugin#165]
cordova-sms-plugin was installed by running `cordova plugin add cordova-sms-plugin` at the CLI. The recommended code listed at https://github.com/cordova-sms/cordova-sms-plugin#using-the-plugin was adopted. When subsequently testing the app, a syntax error displayed stating that: "TypeError: sms.requestPermission is not a function".

When reviewing the local copy of sms.js obtained from the plugin installation process, the `sms.requestPermission` function was not included in the code.  Meanwhile, when reviewing https://github.com/cordova-sms/cordova-sms-plugin/blob/master/www/sms.js, it displays the `sms.requestPermission` function in lines 55-63.

Further investigation showed that the local copies of Sms.java and Sms.m obtained from the CLI installation process omitted a few lines of code that were included in the GitHub versions.

I updated the local copies of sms.js, Sms.java, and Sms.m so that they match the GitHub versions.  Now the app is successfully using cordova-sms-plugin to send SMS messages.  (Thanks for building a great plugin!)

Did i do something wrong during the plugin installation process?  Or does something need to be done on the plugin developer side to make sure the latest code is being included when running `cordova plugin add cordova-sms-plugin`?

**Comment by charliemitchell** [comment]
It looks like this commit 
https://github.com/cordova-sms/cordova-sms-plugin/commit/30d48efd7d8ab5757a818547c418fa4014c5c0cf
is not in any release. Only on master. So if my assumptions are correct, the release will not actually work. Only master will.

**Comment by dbaq** [comment]
I just published a new version on NPM. Thanks for reporting the issue.
