### ISSUE TITLE
iOS after sending SMS through Native SMS app when close half of application screen is white

### ISSUE THREAD

**Issue by rammere** [cordova-sms/cordova-sms-plugin#169]
When send SMS in iOS it goes to native sms app  then you send the SMS , however once I clicked on send ( in the native sms app ) it close the native sms app and goes back to my application with half of my app white screen . I think this is because when the native sms app close the keyboard and the sms message box place push the app up filling their place with white screen.
![whatsapp image 2018-05-23 at 12 44 57 pm](https://user-images.githubusercontent.com/1685788/40417003-6bf9b344-5e87-11e8-8dab-a7b93ce5a736.jpeg)

**Comment by dbaq** [comment]
Looks like a duplicate of https://github.com/cordova-sms/cordova-sms-plugin/issues/22.
