### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by agarrharr** [cordova-sms/cordova-sms-plugin#17]
In the readme you said "Make sure the tests pass", but there aren't any tests, right? Are you planning on adding unit tests? or is that a mistake in the readme?

I have no idea how you would even unit test this plugin, or cordova plugins in general, but if it's possible, I think it's a great idea.

**Comment by dbaq** [comment]
I copy/paste this part of the readme from another project. But we should definitely add unit tests. Even basic ones.

**Comment by agarrharr** [comment]
Great! I'm really interested in this. Post any examples or articles about unit testing cordova plugins that you find here, and let's see what we can do.

**Comment by dbaq** [comment]
I haven't found a lot of things but I looked at the other cordova plugins and they all look pretty much the same. They are only testing the JS part with jasmine, I was more interested in testing the native part.

https://github.com/wildabeast/BarcodeScanner/blob/master/spec/barcodescanner.tests.js
https://github.com/phonegap-build/PushPlugin/blob/master/spec/genericpush.tests.js
https://github.com/MobileChromeApps/zip/blob/master/tests/tests.js
