### ISSUE TITLE
requestPermission does not exist

### ISSUE THREAD

**Issue by 3cees** [cordova-sms/cordova-sms-plugin#170]
Hi,

since a few days, the App doesn't ask for the SMS permissions anymore. (android)
I deleted it and did fresh installs on my phone.
Before that, it asked on runtime for the permission. Now it doesn't.

`this.sms.hasPermission().then((has_permission) => {
      console.log(has_permission);`

returns a `false`. 

My idea was, to ask explicit for the permission. In the docs, this function "requestPermission " is mentioned.
I did a fresh install and that function doesn't exist.
When I check the permission of the app in the settings SMS is disabled.

Many Thanks,
Lars

**Comment by TCookz** [comment]
Ran into the same problem.
fixed it by cloning the plugin directly from github
i.e.
$ cordova plugin rm cordova-sms-plugin --save
$ cordova plugin add https://github.com/cordova-sms/cordova-sms-plugin.git --save

/your_cordova_project/plugins/cordova-sms-plugin/www/sms.js should now contain the following
sms.requestPermission = function(success, failure) {
    // fire
    exec(
        success,
        failure,
        'Sms',
        'request_permission', []
    );
};

**Comment by dbaq** [comment]
Thanks @ThomasCokelaere for the solution, I need to check why the plugin is not up to date on npm.

**Comment by juristr** [comment]
Just had the very same issue. @dbaq did you have a chance looking into this? Maybe do a new release on npm? thx 🙏

**Comment by dbaq** [comment]
I am on vacation until August 1st. I'll push a new npm version when I come
back. Thanks.

**Comment by dbaq** [comment]
I just published a new version on NPM.
