### ISSUE TITLE
phone number needs space formatting?

### ISSUE THREAD

**Issue by r4mst3r** [cordova-sms/cordova-sms-plugin#173]
Hi,

I am doing tests on my android. I am trying to send to number +61412345678

it will not send unless i put the formatting: +61 412 345 678, why is that? my options are android: { intent: '' }

I am on android 8 in my phone and using cordova-android 7

regards

**Comment by dbaq** [comment]
hey @r4mst3r,

The formatting should not matter. Which messaging app do you have on your phone? Have you tried on other phones?

**Comment by dbaq** [comment]
Closing this as no answer, please feel free to reopen it.
