### ISSUE TITLE
Not sending texts after last IOS update

### ISSUE THREAD

**Issue by labstudios** [cordova-sms/cordova-sms-plugin#174]
I had this plugin working - app was released, etc. Then a couple weeks ago there was an IOS update for iPhone 10 and the text feature no longer works. On these devices, the returning message is that the text was canceled (as though the user canceled sending the text), but there was never an option to send or not send; the text app never shows up. 

Any suggestions on how this could be fixed would be appreciated!

**Comment by utleynicole** [comment]
I second this! It would be awesome to get a fix.

**Comment by ghost** [comment]
I second this! It would be awesome to get a fix.

**Comment by dbaq** [comment]
Just got back from vacation. Will try to have a look at that soon. In the meantime, please provide a simple example so I can reproduce the issue (with cordova version, ios version, etc.). Thank you.

**Comment by labstudios** [comment]
My actual send code is pretty basic:

`            sms.send(this.phoneNumber,
                    sendMessage,
                    {
                        android: {
                            intent: 'INTENT'
                        }
                    },
                    this.smsSentSuccessfully.bind(this),
                    this.smsFailure.bind(this)
                );
`

The only other thing I can think of is if there should be some caveat for ios as there is for Android, but I haven't seen such things in the docs.

**Comment by ghost** [comment]
The text feature works fine on Android and was working on ios until a recent update. Now it's seriously holding up the app :/ Any suggestions dbaq?

**Comment by dbaq** [comment]
Any xcode stacktrace? I have been swamped with work recently so it is difficult for me to find time to debug this issue. Any help is welcome.

**Comment by labstudios** [comment]
So, here's the fun information: the phone we saw it fail on is not one I have constant access to. The usual iPhone I use for testing is an old iPhone 5 and it never had the option to update, so the text messaging worked. This morning, I was able to update the phone. After doing so, the text messaging broke, so it definitely has something to do with that update (11.4.1).  All that being said, there is what I see in the debugger:

`Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.

The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

2018-08-24 10:39:27.208279-0600 Backpatt[299:14305] [Common] _BSMachError: port 7207; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"

2018-08-24 10:40:00.010898-0600 Backpatt[299:14305] Status bar could not find cached time string image. Rendering in-process.

2018-08-24 10:40:05.184198-0600 Backpatt[299:14305] Message cancelled.

2018-08-24 10:40:43.023554-0600 Backpatt[299:14788] TIC Read Status [2:0x0]: 1:57

2018-08-24 10:40:43.023666-0600 Backpatt[299:14788] TIC Read Status [2:0x0]: 1:57`

That "Message cancelled" is what I see every time I click the button to send the text message. It used to open the text app and wrap the text I wanted inside of it. Now, based on the message I am seeing, it acts like it opened the text app, and the user decided not to send the text. Except it doesn't open the app. It just cancels immediately.

Here is another grouping where I tried repeatedly:

`2018-08-24 10:55:08.198932-0600 Backpatt[299:14305] Message cancelled.

2018-08-24 10:55:15.296573-0600 Backpatt[299:14305] Message cancelled.

2018-08-24 10:55:17.258336-0600 Backpatt[299:14305] Message cancelled.

2018-08-24 10:55:20.997458-0600 Backpatt[299:14305] Message cancelled.

2018-08-24 10:55:23.073771-0600 Backpatt[299:14305] Message cancelled.`

Any thoughts on this one?

**Comment by dbaq** [comment]
I looked for the root cause but no luck so far. Could this old issue be related: https://github.com/cordova-sms/cordova-sms-plugin/issues/94?

**Comment by labstudios** [comment]
Yikes! It totally was. I was double checking my variable to make sure it was a string (as suggested) only to find it was using an old variable that wasn't set anymore. I'm wondering if maybe it was a merge conflict fixed incorrectly. Sooooo sorry! It really seemed to spring up with the Apple update, but could have been coincidental to builds, merges, etc.

**Comment by dbaq** [comment]
I am glad you found your issue. Feel free to open another issue if you need help with anything else.
