### ISSUE TITLE
Cant Send Text With String + Number

### ISSUE THREAD

**Issue by edoofx** [cordova-sms/cordova-sms-plugin#176]
if i type "**A little bit message.**" plugin can send sms normally
but, when im using "**A little bit message. Model: ABCD EEE9987 Serial: 123456789**" this plugin not work

Cordova 8
Android 7

**Comment by dbaq** [comment]
hello @edoofx,

This seems very strange. Can you please check the logcat logs via `$ adb logcat` for a stracktrace?

Thank you.

**Comment by dbaq** [comment]
Closing this since no answer, please feel free to reopen it if needed.
