### ISSUE TITLE
Read SMS

### ISSUE THREAD

**Issue by ukenpachi** [cordova-sms/cordova-sms-plugin#177]
Hi was just wondering if you can read SMS using this plugin? Basically, I will be sending SMS using this plugin or Twilio to another device but from the device which receives the SMS, I want to read it. Is it possible with this plugin?

**Comment by dbaq** [comment]
hello @ukenpachi, this plugin is "send-only". But other Cordova plugins (more complex plugins) manage reading and sending messages.
