### ISSUE TITLE
Trouble installing plugin

### ISSUE THREAD

**Issue by allankiezel** [cordova-sms/cordova-sms-plugin#178]
I'm running `ionic cordova plugin add cordova-sms-plugin` but keep getting this output. Any suggestions?

 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: npm: Command failed with exit code 1 Error output:
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html>
npm ERR! <head>
npm ERR! <title>Fastly error: unknown domain</title>
npm ERR! </head>
npm ERR! <body>
npm ERR! Fastly error: unknown domain. Please check that this domain has been added to a service.
npm ERR! </body>
npm ERR! </html>

**Comment by dbaq** [comment]
hello @allankiezel, were you able to solve your problem?

**Comment by dbaq** [comment]
Closing this since no answer was provided. Feel free to reopen if the problem persists.
