### ISSUE TITLE
Can't make it send an sms with my code?

### ISSUE THREAD

**Issue by Kiam9000** [cordova-sms/cordova-sms-plugin#18]
Hey guys!

I tried to use this very nice plugin, but I can't make it send an sms?

My code is

var app = {

```
sendSms: function() {
    var number = '28159518';
    var message = 'In need of help at these cords: ' + cords; (Cords is set earlier with geoposition)
    alert(number); (shows the alert correct)
    alert(message); (shows the alert and with the correct data)

    //CONFIGURATION
    var options = {
        replaceLineBreaks: false, // true to replace \n by a new line, false by default
        android: {
            intent: 'INTENT'  // send SMS with the native android SMS messaging
            //intent: '' // send SMS without open any other app
        }
    };

    alert("Test before send"); (shows the alert correct)
    var success = function () { alert('Message sent successfully'); };
    var error = function (e) { alert('Message Failed:' + e); };
    sms.send(number, message, options, success, error);
    alert("Test after send"); 
    (This alert or the succes/error never comes, which leads me to think it never execute sms.send?)
}  
```

};

Hope you can help me with this little issue

Kind regards,
Maik

**Comment by dbaq** [comment]
hey @Kiam9000,

make sure the plugin is installed by running the following command `$ cordova plugins list`, you should be the plugin listed.

also how are you testing? on a real device? which device? ios? android? wp8?

try to give us all the details you can :)

**Comment by Kiam9000** [comment]
Hey @dbaq 

I checked and it is installed

I am testing on a real device, Oneplus One Android

**Comment by dbaq** [comment]
Other questions:
- any custom rom on your android or is it the regular android installed? which version of android?
- cordova version please? 
- can you try to create a basic cordova app via cordova create, add the plugin, add the platform, update the code and use the default example? 
- can you test your code on another device?

**Comment by Kiam9000** [comment]
Regular android installed, version 4.4.4 (Cyanogen OS is installed as part of oneplus one, version 11.0-xnph05q)

Cordova version 4.2.0

No only got android available to test on proper device

A simple re-create of the example does work...I may have an idea of why mine does not work now. I will report back when tested this idea I got

**Comment by agarrharr** [comment]
I have another question. Are you getting any errors in the javascript console?

**Comment by Kiam9000** [comment]
No I do not

**Comment by agarrharr** [comment]
You do have access to the javascript console, correct? For example you can run `alert('hi');` and an alert will pop up in your app on your phone?

**Comment by Kiam9000** [comment]
Yeah I do have that, but no errors received

UPDATE: @dbaq  & @aharris88 I have rebuild my project from scratch and now it works perfectly!
I have no idea where the issue specific was unfortunely, but may be a mistyping from my side as well

Thx for the quick respose and love the plugin.

Kind regards,
Maik

**Comment by dbaq** [comment]
@Kiam9000 glad it works. Let us know if you have over issues.
