### ISSUE TITLE
ios 12 error on sendSms

### ISSUE THREAD

**Issue by Pixy123** [cordova-sms/cordova-sms-plugin#180]
Hi, I have created new app from zero. When I try to send sms on ios 12.0 (16A366)  emulator I receive "Message Failed: SMS Text not available".
I have try force sms text with this code but not resolve.
` sendSms: function() {
    	var number = "+393401234567";
        var message = "test";
        console.log(" prova invio sms a number=" + number + ", message= " + message);
        //CONFIGURATION
        var options = {
            replaceLineBreaks: false, // true to replace \n by a new line, false by default
            android: {
                intent: 'INTENT'  // send SMS with the native android SMS messaging
                //intent: '' // send SMS without open any other app
            }
        };
        var success = function () { alert('Message sent successfully'); };
        var error = function (e) { alert('Message Failed:' + e); };
        sms.send(number, message, options, success, error);
    }`

Attachment of Xcode error trace
[xcodeError.txt](https://github.com/cordova-sms/cordova-sms-plugin/files/2428692/xcodeError.txt)

Can you help me?
Cordova version 8.0.0
Ios platform 4.5.5

**Comment by Pixy123** [comment]
can it be the simulator's fault? I don't have hardware with ios 12

**Comment by dbaq** [comment]
sorry @Pixy123 for the delay, but yes, it is due to the simulator (see code: https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/ios/Sms.m#L11)

You need to test on real device.
