### ISSUE TITLE
text msg is not sent but displayed in android native text app as a draft

### ISSUE THREAD

**Issue by lhughes33472** [cordova-sms/cordova-sms-plugin#187]
Text msg is never sent and appears in the native android  text  app, thus requiring it to be sent from the native app. How can the msg be sent bypassing the native app?

Thanks,
Larry

**Comment by imjeffparedes** [comment]
Android Version 8.1
PhoneGap 0.4.5
Cordova Version 8.0.0

This is my problem too. 
The plugin said the sms is sent via SMS.sendSMS
But checking on the native app, it is not and has to manually resend it.

**Comment by dbaq** [comment]
Hi guys,

Any stacktrace in logcat? `$ adb logcat`

**Comment by dbaq** [comment]
bump

**Comment by dbaq** [comment]
Closing this one since no reply. Feel free to reopen it.
