### ISSUE TITLE
Android intent not working

### ISSUE THREAD

**Issue by Diptyajit1994** [cordova-sms/cordova-sms-plugin#188]
Hi whenever i set android **intent :''**  the application closes it self.
Code : 
```
function checkSMSPermission() {
    var success = function (hasPermission) { 
        if (hasPermission) {
            var number = document.getElementById('numberTxt').value.toString();
            var message = document.getElementById('messageTxt').value;
            console.log("number=" + number + ", message= " + message);

           //CONFIGURATION
            var options = {
                replaceLineBreaks: false, 
                android: {
                    intent: ''  
                }
            };

            var success = function () { alert('Message sent successfully'); };
            var error = function (e) { alert('Message Failed:' + e); };
            sms.send(number, message, options, success, error);
        }
        else {
            requestSMSPermission()
        }
    };
    var error = function (e) { alert('Something went wrong:' + e); };
    sms.hasPermission(success, error);
}

function requestSMSPermission() {
    var success = function (hasPermission) { 
        if (!hasPermission) {
            sms.requestPermission(function() {
                console.log('[OK] Permission accepted')
                checkSMSPermission()
            }, function(error) {
                console.info('[WARN] Permission not accepted')
                // Handle permission not accepted
            })
        }
    };
    var error = function (e) { alert('Something went wrong:' + e); };
    sms.hasPermission(success, error);
}
```

**Comment by dbaq** [comment]
Hi there,

can you please check your logcat logs please? (via `$ adb logcat`). You should see the stack trace.

**Comment by Diptyajit1994** [comment]
Hi @dbaq i was able to send sms with android 5 devices internally with "android: { intent: ''  }" but when it comes to android 6+ i am always getting the error.
`var **error** = function (e) { alert('Message Failed:' + e); };
            sms.send(number, message, options, success, **error**);`

**Comment by dbaq** [comment]
hey @Diptyajit1994,

Have you asked for the permission? I am talking about `checkSMSPermission`, `requestSMSPermission`.

**Comment by Diptyajit1994** [comment]
Hi @dbaq  yes i did asked for the permission  but the issue is it is getting false all the time as i have removed the uses-permission android:name="android.permission.SEND_SMS"  from AndroidManifest.xml file

I am building the application in developer mode with cordova run android in my mobile device for testing and when i check my application in android 6+ devices it giving me the error while sending a sms with "intent: ' ' ".

**Comment by dbaq** [comment]
What android target (API level) are you using for the build? You might need the permission in the SENS_SMS permission in the plugin.xml file.

**Comment by krishnarout** [comment]
> Hi @dbaq yes i did asked for the permission but the issue is it is getting false all the time as i have removed the uses-permission android:name="android.permission.SEND_SMS" from AndroidManifest.xml file
> 
> I am building the application in developer mode with cordova run android in my mobile device for testing and when i check my application in android 6+ devices it giving me the error while sending a sms with "intent: ' ' ".

hi, can you please tell me how u have sent msg in ionic4 by using cordova sms plugin please m struggling for last 15days? I am not using android permission plugin only using sms plugin and here is my code: 
  sendSMSfunction(){
    var options = {
      replaceLineBreaks: false,
      android: {
        intent: 'INTENT' 
      }
  }
  this.sms.send('+918249921275', 'Hello world!', options);
}
please tell how to send sms ?thank u

**Comment by krishnarout** [comment]
> Hi @dbaq i was able to send sms with android 5 devices internally with "android: { intent: '' }" but when it comes to android 6+ i am always getting the error.
> `var **error** = function (e) { alert('Message Failed:' + e); }; sms.send(number, message, options, success, **error**);`

hi, could you please tell me how u send messages ?I am using ionic 4  and installed only cordova sms plugin not using android permission plugin .here is my code snippet :
  sendSMSfunction(){
    var options = {
      replaceLineBreaks: false,
      android: {
        intent: 'INTENT' 
      }
  }
  this.sms.send('+918249921275', 'Hello world!', options);
} 
please tell me how to send sms in ionic4 ?thank you

**Comment by Diptyajit1994** [comment]
@krishnarout  Try this..
`sendSMSfunction() {
        var success = function (hasPermission) { 
            if (hasPermission) {
                var number = document.getElementById('numberTxt').value.toString(); 
                var message = document.getElementById('messageTxt').value;
        console.log("number=" + number + ", message= " + message);

        //CONFIGURATION
        var options = {
            replaceLineBreaks: false,
            android: {
                intent: 'INTENT' 
            }
        };

        var success = function () { alert('Message sent successfully'); };
        var error = function (e) { alert('Message Failed:' + e); };
        sms.send(number, message, options, success, error);
            }
            else {
                requestSMSPermission()
            }
        };
        var error = function (e) { alert('Something went wrong:' + e); };
        sms.hasPermission(success, error);
    },
    function requestSMSPermission() {
        var success = function (hasPermission) { 
            if (!hasPermission) {
                sms.requestPermission(function() {
                    console.log('[OK] Permission accepted')
                     sendSMSfunction()
                }, function(error) {
                    console.info('[WARN] Permission not accepted')
                    
                })
            }
        };
        var error = function (e) { alert('Something went wrong:' + e); };
        sms.hasPermission(success, error);
    }`

**Comment by krishnarout** [comment]
Hi,
     Thanks for your reply .Trying and let u know.

**Comment by krishnarout** [comment]
hi,
     I have tried this method still no result.please tell me how to send
sms.

thanks
krishna

**Comment by Diptyajit1994** [comment]
@krishnarout  can u share your code.

**Comment by krishnarout** [comment]
Sure

**Comment by krishnarout** [comment]
please check once please.

**Comment by Diptyajit1994** [comment]
@krishnarout  share your current set of code that u are using in your cordova application  in a separate post. It will be more helpful.

**Comment by krishnarout** [comment]
same code only m using.

**Comment by dbaq** [comment]
Closing this one since no reply. Feel free to reopen it.
