### ISSUE TITLE
Unhandled Promise rejection: User has denied permission ; Zone: <root> ; Task: null ; Value: User has denied permission undefined 

### ISSUE THREAD

**Issue by krishnarout** [cordova-sms/cordova-sms-plugin#191]
I am using ionic 4. while I am clicking on send button I am getting this error :"Unhandled Promise rejection: User has denied permission ; Zone: <root> ; Task: null ; Value: User has denied permission undefined" 
here is code snippet:
 sendSms(){

this.sms.send('+91xxxxxx', 'Hello world!');
  }
I am using only cordova-sms-plugin  not using android permission plugin .please suggest me how to solve this issue.

**Comment by krishnarout** [comment]
here is my code snippet:

home.ts:
import { Component } from '@angular/core';
import { SMS } from '@ionic-native/sms/ngx';



@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  app:any
  constructor(private sms: SMS) { }


  sendSMSfunction(){
    var options = {
      replaceLineBreaks: false,
      android: {
        intent: '' 
      }
  }
  this.sms.send('+918249921275', 'Hello world!', options);
}

**Comment by dbaq** [comment]
Closing because you asked same question in another issue.

**Comment by jsplate** [comment]
@dbaq It would have been nice to know the issue...

**Comment by jsmith347** [comment]
> @dbaq It would have been nice to know the issue...

For me, I managed to get it working by adding the following under the Android platform section in the config.xml:
```

        <config-file parent="/manifest" target="AndroidManifest.xml" xmlns:android="http://schemas.android.com/apk/res/android">
            <uses-permission android:name="android.permission.SEND_SMS" />
        </config-file>
```
