### ISSUE TITLE
Plugin should use CordovaInterface.getThreadPool().

### ISSUE THREAD

**Issue by demobiel** [cordova-sms/cordova-sms-plugin#192]
When I try to run sms.requestPermission() I got immediately the error callback. I am never asked if I would allow to send SMS or not.

I run the following code:
```
requestSMSPermission: function() {
        var success = function (hasPermission) { 
            if (!hasPermission) {
                alert("about to ask for permission");
                sms.requestPermission(function() {
                    alert('[OK] Permission accepted')
                }, function(error) {
                    alert('[WARN] Permission not accepted')
                    // Handle permission not accepted
                })
            }
        };
        var error = function (e) { alert('Something went wrong:' + e); };
        sms.hasPermission(success, error);
    }
```
And so I get an alert "about to ask permission", and immediately "[Warn] Permission not accepted".

I followed all the tips on this issue: https://github.com/cordova-sms/cordova-sms-plugin/issues/189,
but no success.

When I inspect the catlog, I see the following line:
03-07 10:14:43.963  6498  6605 W PluginManager: THREAD WARNING: exec() call to Sms.request_permission blocked the main thread for 41ms. Plugin should use CordovaInterface.getThreadPool().

I am using cordova 7.1.1 and latest version of the plugin.

Kind regards
Andries

**Comment by dbaq** [comment]
hey @demobiel,

Thanks for reporting the issue. Feel free to contribute, it should be fairly easy to implement.

**Comment by demobiel** [comment]
Hi dbaq,

I think I actually reported 2 issues:
first: sms.requestPermission(success, error) always calls error in my case

because of that I looked into the log and saw this error, but apparently it is only a warning.

I think I can solve the second one, and I am willing to contribute, however I have no idea why this falls down each time to error.

Adding the intent into the manifest works, but of course this will not get it on the Google store...

**Comment by vvpolyakov** [comment]
I tried all possible versions of SDK and Phonegap versions, as well as different phones, and constantly get an error  "_User has denied permission_"
This error returns both  _sms.requestPermission()_ and _sms.send()_
Plugin version 1.0.0
I'm testing mostly on Android 7.0
Compile through Phonegap Build service
Can anyone have a working example?

**Comment by dbaq** [comment]
I don't know about phonegap.

Have you read https://github.com/cordova-sms/cordova-sms-plugin/issues/183?

The only recent change is this commit: https://github.com/cordova-sms/cordova-sms-plugin/commit/ecf4d094d89cee78d3eaeb16ac9cd1582511e1e9

**Comment by dbaq** [comment]
To make it work with PhoneGap, you need to add the `SEND_SMS` permission manually if you are using `android: { intent: '' }`:

See https://github.com/cordova-sms/cordova-sms-plugin/pull/198
