### ISSUE TITLE
SMS cordova plugin INTENT is not working  Ionic Native

### ISSUE THREAD

**Issue by AbrahamGarcia240** [cordova-sms/cordova-sms-plugin#195]
Hello everyone

I am using Ionic 4 to build an app that is meant to send an emergency SMS, therefore I need it to be sent programatically without entering into the native SMS app.

Im using the following code:

```javascript
async sendSMS(){
    this.androidPermissions.checkPermission(this.androidPermissions.PERMISSION.SEND_SMS).then(
      result => console.log('Has permission?'+result.hasPermission),
      err => this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.SEND_SMS )
      );
    var options = {
            replaceLineBreaks: true, // true to replace \n by a new line, false by default
            android: {
                //intent: 'INTENT'  // send SMS with the native android SMS messaging
               intent: '' // send SMS without opening any other app
            }
        };
        try{
        await this.sms.send(this.phoneNumber.toString(),this.textMessage,options);
        console.log("sent");
        this.mostrarToast("mensage sent");
      }
      catch(e){
        console.log(JSON.stringify(e));
        console.log(e);
        this.mostrarToast(e);
      }
  }
```

Nevertheless I get this error in my logcat

`2019-03-19 21:17:12.255 11786-11786/io.ionic.starter I/chromium: [INFO:CONSOLE(168)] "Has permission?", source: http://localhost:8080/home-home-module.js (168)
2019-03-19 21:17:12.322 11786-11786/io.ionic.starter I/chromium: [INFO:CONSOLE(187)] ""User has denied permission"", source: http://localhost:8080/home-home-module.js (187)
2019-03-19 21:17:12.322 11786-11786/io.ionic.starter I/chromium: [INFO:CONSOLE(188)] "User has denied permission", source: http://localhost:8080/home-home-module.js (188)
`

**Comment by dbaq** [comment]
Hi @AbrahamGarcia240,

Can you try adding to your `plugin.xml`?

```
            <uses-permission android:name="android.permission.SEND_SMS" />
            <uses-permission android:name="android.permission.READ_PHONE_STATE" />
```

We removed it recently (https://github.com/cordova-sms/cordova-sms-plugin/commit/ecf4d094d89cee78d3eaeb16ac9cd1582511e1e9) due to the new google store policy. Let me know if that solves your issue.

Thanks

**Comment by dbaq** [comment]
Closing this one since no reply. Feel free to reopen it.
