### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by NorthFred** [cordova-sms/cordova-sms-plugin#197]
I am not able to send SMS from my Android project:

> TypeError: Object(...) is not a function

Ionic info:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\f_ver\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, browser 5.0.4

Any ideas?

**Comment by pr0thean** [comment]
I have the same  problem. Any ideas? I tried these methods from the link but still the same...
https://stackoverflow.com/questions/53625774/type-error-object-not-a-function-when-adding-sms-plugin-ionic

**Comment by dbaq** [comment]
Hi @NorthFred , @pr0thean,

Sorry, but it looks like this is an issue with typescript/ionic-native not with this Cordova plugin. I am going to close this one as it is not directly related.

Best,
@dbaq
