### ISSUE TITLE
Do not send sms the permission is not added in the AndroidManifest.xml

### ISSUE THREAD

**Issue by Leo1305Pineda** [cordova-sms/cordova-sms-plugin#199]
in el file plugin.xml
`<config-file target="AndroidManifest.xml" parent="/manifest">
            <uses-feature android:name="android.hardware.telephony" android:required="false" />
 </config-file>`
aggregate 
`<uses-permission android:name="android.permission.SEND_SMS"/>`

**Comment by dbaq** [comment]
Closing this one, see my comment on your PR. Thanks again for contributing.
