### ISSUE TITLE
Using phonegap build

### ISSUE THREAD

**Issue by dbaq** [cordova-sms/cordova-sms-plugin#2]
need to check availability of this plugin on phonegap build.

**Comment by agarrharr** [comment]
I think this could be done now. It was a problem before because it seemed that someone had already tried to register my plugin with the old github url.

**Comment by dbaq** [comment]
I will do that on Monday.

**Comment by agarrharr** [comment]
Here is the documentation on how to add a plugin to Phonegap Build: http://docs.build.phonegap.com/en_US/developer_contributing_plugins.md.html#Contributing%20Plugins

**Comment by dbaq** [comment]
Thanks

**Comment by dbaq** [comment]
Huuuuu

`Phonegap build: There was recently a policy change so if you are not a paid subscriber, you can't submit plugins.`

**Comment by agarrharr** [comment]
I can submit it then. But if I try right now it says "Error index.html not found". So we need to do this:

```
To check whether your plugin is packaged correctly for each supported platform:

Create a new Cordova project for that platform. Edit the generated index.html file to reference and use your plugin
Run the correct plugman command. For instance, if you're installing a plugin stored in /Users/ramen/dev/plugin into an iOS project stored in /Users/ramen/dev/my_project, run:

plugman -platform ios /Users/ramen/dev/my_project /Users/ramen/dev/plugin

Verify that the project can build without error, that the plugin is included, and that any JavaScript code using the plugin executes correctly.
```

**Comment by dbaq** [comment]
I tried, I am able to run the plugman command without any issue. I don't see why we need an index.html. I've never done that before, is it cloning the repo?

**Comment by agarrharr** [comment]
Oh, actually I was submitting to the wrong form. This is the correct form: https://build.phonegap.com/plugins#add

Now the error says: `Please choose another plugin ID. This namespace is reserved`

**Comment by dbaq** [comment]
I was afraid of that, we are using the reserved namespace com.phonegap.xxxx, I need to look how we can change the namespace of the plugin.

**Comment by dbaq** [comment]
@aharris88 I changed the plugin id. I thought it was way more complicated than that. Could you try to submit the plugin one more time please?

**Comment by agarrharr** [comment]
Ok, I submitted it. Here it is: https://build.phonegap.com/plugins/1999

**Comment by dbaq** [comment]
Great, thanks @aharris88.

Does that mean we have to submit it again every time we push a new version or do we just have to update the version value in package.json?

Also I am reopening this one as a reminder for myself to update the documentation. I will close it after.

**Comment by agarrharr** [comment]
I'm guessing that all you need to do is update the version in plugin.xml and add a git tag like they do here: https://github.com/phonegap-build/PushPlugin/releases

**Comment by dbaq** [comment]
Added to the documentation via f8db618bbd56a623dbb70ed293126b94078adce7.

**Comment by agarrharr** [comment]
Turns out that you have to re-submit here every time it updates: https://build.phonegap.com/plugins#add
