### ISSUE TITLE
When SMS has not been sent, the error callback should be called

### ISSUE THREAD

**Issue by khayargoli** [cordova-sms/cordova-sms-plugin#202]
Hi All,

I am using sms to send using the intent like: 
```
var options = {
  android: {
       intent: 'INTENT'  // send SMS with the native android SMS messaging
   }
};
sms.send(number, message, options, success, error);
```

The app opens the default intent of messaging, but the user can cancel the process and go back to the app as well in this case the error call back should be called instead of success.

Thanks

**Comment by dbaq** [comment]
hey @biswas123, 

I am currently on vacation so I have limited ways to help you out with limited internet access. 

It seems you are facing something similar to https://github.com/cordova-sms/cordova-sms-plugin/issues/26. Could you confirm?

If it is the case, nothing has changed AFAIK, you would have to take into consideration in your user flow.

Best,
@dbaq

**Comment by dbaq** [comment]
Closing this one since no answer.
