### ISSUE TITLE
Error : SMS plugin Ionic

### ISSUE THREAD

**Issue by snehalv** [cordova-sms/cordova-sms-plugin#206]
I am new to Ionic and trying to learn from YouTube.

Please help me to install sms-plugin.

I am Facing error for the command 
- cordova plugin add https://github.com/cordova-sms/cordova-sms-plugin.git

 cordova.cmd plugin add cordova-sms-plugin exited with exit code 1.

**Comment by dbaq** [comment]
hi @snehalv,

Can you please share more logs? Use the verbose option (`--verbose` I believe). Can you also include the version of the ionic you are using?

**Comment by snehalv** [comment]
@dbaq 
tried to run with --verbose also but same issue.
i am using version 5.2.6

now facing error 

ionic cordova plugin add cordova-plugin-contacts
> cordova.cmd plugin add cordova-plugin-contacts
npm: Command failed with exit code 1 Error output:
npm ERR! code ECONNRESET
npm ERR! network tunneling socket could not be established, cause=connect ETIMEDOUT 
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!    
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd plugin add cordova-plugin-contacts exited with exit code 1.

**Comment by dbaq** [comment]
Hi there, 

As you can see, it is a network error on your side. Can you access npm?

**Comment by dbaq** [comment]
Closing this since no reply.
