### ISSUE TITLE
Unable to send SMS in Phonegap app. No action when 'send SMS' button clicked  

### ISSUE THREAD

**Issue by sankari123** [cordova-sms/cordova-sms-plugin#207]
config.xml

Index.htm

<script type="text/javascript" src="cordova.js"></script> <script>
	function onDeviceReady() {
		  app.checkSMSPermission();
}

function alertDismissed() {
alert('Invalid');
}

var app = {
sendSms: function() {
alert('click');
var number = document.getElementById('numberTxt').value;
var message = document.getElementById('messageTxt').value;
alert(number);
alert(message);
var intent = 'INTENT'; //leave empty for sending sms using default intent
var success = function () { alert('Message sent successfully'); };
var error = function (e) { alert('Message Failed:' + e); };
sms.send(number, message, intent, success, error);
}
};

var app = {
checkSMSPermission: function() {
var success = function (hasPermission) {
if (hasPermission) {
sms.send(number, message, intent, success, error);
}
else {
// show a helpful message to explain why you need to require the permission to send a SMS
// read http://developer.android.com/training/permissions/requesting.html#explain for more best practices
}
};
var error = function (e) { alert('Something went wrong:' + e); };
sms.hasPermission(success, error);
},
requestSMSPermission: function() {
var success = function (hasPermission) {
if (!hasPermission) {
sms.requestPermission(function() {
console.log('[OK] Permission accepted')
}, function(error) {
console.info('[WARN] Permission not accepted')
// Handle permission not accepted
})
}
};
var error = function (e) { alert('Something went wrong:' + e); };
sms.hasPermission(success, error);
}
};

</script>
</head>
 
<body> 
	<center>Send SMS</center>
	<input id="numberTxt" placeholder="Enter mobile number" value="" type="tel" />
<textarea id="messageTxt" placeholder="Enter message"></textarea>
 
<input type="button" onclick="'app.sendSms();" value="Send SMS" /> 
 
</body>
</html>

**Comment by sankari123** [comment]
I'm testing on Samsung 5 & 6

**Comment by dbaq** [comment]
Closing this since no reply.
