### ISSUE TITLE
intent: '' does not work.

### ISSUE THREAD

**Issue by sankari123** [cordova-sms/cordova-sms-plugin#208]
I am creating a phonegap app. I want to send sms directly without going into native sms app. I tried intent: ''. I get the message ' Message failed:User has denied permission. any changes to be done in config.xml? pl help. I gave all permissions to the app manually.

**Comment by dbaq** [comment]
Good morning @sankari123,

Have you checked this issue https://github.com/cordova-sms/cordova-sms-plugin/issues/183?

**Comment by dbaq** [comment]
Closing this since no answer.
