### ISSUE TITLE
Cannot send sms to multiple person at once

### ISSUE THREAD

**Issue by Nikhil-Daffodil** [cordova-sms/cordova-sms-plugin#211]
Hi , i'm unable to send sms to multiple person at once.
`
    let phone = contactList.map(({phoneNumber}) => phoneNumber);<--  Array of phone number
           this.sms.send(phone, message).then(() => {
            console.log("Message sent");            
          }).catch(err => {
            console.log(err);            
          })
`

It takes only first number of the array

**Comment by dbaq** [comment]
Please see this one https://github.com/cordova-sms/cordova-sms-plugin/issues/132. You need to iterate over the array and send the SMS one by one.
