### ISSUE TITLE
Send iOS message without opening native keyboard

### ISSUE THREAD

**Issue by sts-ryan-holton** [cordova-sms/cordova-sms-plugin#212]
Hi, I'd like to be able to send a SMS message using this plugin for both iOS and Android without opening the native keyboard and messaging app, how can I achieve this for iOS? I've set: `intent` in my options to be an empty string.

I understand that [this](https://github.com/cordova-sms/cordova-sms-plugin/issues/35) says it can't be done, so any suggestion on a work around?

**Comment by dbaq** [comment]
Hi @sts-ryan-holton, unfortunately, it is an iOS limitation. It is not possible to send a message without opening the native messaging app.
