### ISSUE TITLE
Sms problem with Samsung Galaxy S7 Edge

### ISSUE THREAD

**Issue by Hideikey** [cordova-sms/cordova-sms-plugin#213]
The plugin works, but the problem is when try to create a second message whitout close the  messages app native.

This not have the Body of the message, only open the app of messages.

Tested with https://developer.samsung.com/remote-test-lab

**Comment by dbaq** [comment]
hey @Hideiki, thanks for reporting an issue. Do you have a stack trace? A way to reproduce the issue? I don't own a Galaxy S7 edge, so I am going to need more details on this one.

**Comment by Hideikey** [comment]
Forget it, I found out that the same messaging app was the problem, the version 4, Testing with the version 5 or others apps the problem not happen. I think is ok close the post
