### ISSUE TITLE
Intent option

### ISSUE THREAD

**Issue by legagneur-matthieu** [cordova-sms/cordova-sms-plugin#214]
Hi !
when I use 
`android: {intent: ''}`
my app crash immediately when I try to send SMS with.
another option for send SMS without the native SMS app confirmation ?

**Comment by dbaq** [comment]
Hi there,

Have you looked into other closed issues like #183, #208, #78, or #155?

**Comment by legagneur-matthieu** [comment]
Ok I havn't add android.permission.READ_PHONE_STATE. now it work
I made a pull request for precise it in readme.md

**Comment by dbaq** [comment]
I merged your PR. Thanks again for taking the time to do this.
