### ISSUE TITLE
iOS-question: Send sms via iMessage with the Apple ID instead of the telephone number

### ISSUE THREAD

**Issue by Utz1** [cordova-sms/cordova-sms-plugin#216]
I wonder, if it is possible to use the Apple ID instead of a telephone number?
When sending a message on iOS through iMessage app, this is a way to send Messages without a telephone card if you are connected to a WiFi network.
With my little app, I want the user to send menu orders as text to always the same iOS device of a restaurant.

**Comment by dbaq** [comment]
hi @Utz1, thanks for opening an issue.

I don't have any bandwidth to support/add this feature right now but I am more than happy to merge any contributions.
