### ISSUE TITLE
getting MessageComposeResultSent response when sms sending failed.

### ISSUE THREAD

**Issue by prameela-reddy** [cordova-sms/cordova-sms-plugin#220]
I am using MFMessageComposeViewController to send sms within my app. Everything is correct until i try to get the result of the operation. Actually the Message sending failed as It can be seen in the SMS native app (I have no sms balance), but I get MessageComposeResultSent in - (void)messageComposeViewController:(MFMessageComposeViewController *)controller didFinishWithResult:(MessageComposeResult)result.

**Comment by dbaq** [comment]
I believe the way it works is that the iOS native app will return success even the SMS hasn't been delivered. There is no way to verify whether the SMS was delivered.
