### ISSUE TITLE
Open sms app with longer text, Ionic toolbar disappears.

### ISSUE THREAD

**Issue by umairrafiq1133** [cordova-sms/cordova-sms-plugin#222]
I am using this plugin to send sms from my app. When I send a text which is shorter, everything works as expected but when text is longer and sms app opens, coming back to app will hide the toolbar irrespective of whether I sent the sms or not. When inspected in Safari, I can see the toolbar if I add padding-top from `ion-safe-area-top` to `162px`.

**Comment by umairrafiq1133** [comment]
For now I have fixed with some css.

```
sms(phoneNumbers: string[], message: string) {
		return new Promise((resolve, reject) => {
			const options = {
				android: {
					intent: 'INTENT',
				},
			};

			document.body.style.height = '100%';
			document.body.style.marginTop = '0px';

			this.smsPlugin
				.send(phoneNumbers, this.parseMessage(message), options)
				.then(
					() => {
						resolve('success');
					},
					() => {
						reject('error');
					}
				)
				.finally(() => {
					setTimeout(() => {
						const bodyHeight = document.body.offsetHeight;
						const deviceHeight = window.screen.height;
						document.body.style.marginTop = bodyHeight - deviceHeight + 'px';
						document.body.style.height = deviceHeight + 'px';
					}, 200);
				});
		});
	}
```

**Comment by umairrafiq1133** [comment]
I have created a public repository and reproduced the issue.
Here's the link to repo.
https://github.com/umairrafiq1133/ionic-view-bug

https://user-images.githubusercontent.com/18613802/139843085-8004c513-5857-4e7b-9744-27c18a811d7c.mp4

**Comment by dbaq** [comment]
hey @umairrafiq1133, thanks for all the details and the example. Have you posted the issue on the ionic repository? this plugin has no control over the rendering in the ionic webview unfortunately.

**Comment by umairrafiq1133** [comment]
@dbaq Yes I have posted on ionic repo as well.

**Comment by umairrafiq1133** [comment]
@dbaq It was an ionic issue and is resolved. https://github.com/ionic-team/ionic-framework/issues/24135
