### ISSUE TITLE
Publish to the Cordova Plugin Registry

### ISSUE THREAD

**Issue by agarrharr** [cordova-sms/cordova-sms-plugin#23]
Here's the Cordova Plugin Registry:

http://plugins.cordova.io/

And here's how to submit:

http://cordova.apache.org/docs/en/edge/guide_hybrid_plugins_index.md.html#Plugin%20Development%20Guide

**Comment by agarrharr** [comment]
I went ahead and submitted with my username: aharris88. Here is the listing: http://plugins.cordova.io/#/package/com.cordova.plugins.sms

We will need to update this anytime there is a change to the plugin.

**Comment by dbaq** [comment]
Ok good job :+1:

**Comment by agarrharr** [comment]
I updated to v0.1.2 with the `plugman publish` command.

**Comment by satyagvns** [comment]
@aharris88 @dbaq 

Thanks a lot for your support on this.

My Repo : https://github.com/shainfotech/abhaya

I am using build.phonegap.com to generate my apk file. My mobile is google nexus 5.

Still I am facing the same problem. it is opening my native message app (hangouts). Do I need to change anything in my phone settings? or anything I need to change in my code?

Thanks,
Satya

**Comment by aharris88** [comment]
I think you commented on the wrong issue?
