### ISSUE TITLE
Update listing on ngCordova

### ISSUE THREAD

**Issue by agarrharr** [cordova-sms/cordova-sms-plugin#24]
The ngCordova sms plugin is still pointing to the outdated version of this plugin. It should be updated.

http://ngcordova.com/docs/plugins/sms/

I submitted an issue here:

https://github.com/driftyco/ng-cordova/issues/676

but maybe we should just go ahead and submit a pull request.

**Comment by dbaq** [comment]
I opened two PR (one for the source code, one for the docs)

https://github.com/driftyco/ng-cordova/pull/691
https://github.com/driftyco/ng-cordova/pull/692

**Comment by agarrharr** [comment]
It looks like your pull requests got merged.
