### ISSUE TITLE
Android immediately passes success back to app?

### ISSUE THREAD

**Issue by jnorris441** [cordova-sms/cordova-sms-plugin#26]
The iOS composer waits to see if the message was sent or cancelled and fires the right callback. The Android version immediately fires success whether they end up sending or not. 

There is not a way to make Android behave like iOS correct?

(this is using INTENT)

**Comment by dbaq** [comment]
Hi @jnorris441,

Unfortunately, this is a limitation of Android right now, we can't get the result after starting the new activity.

We are using ACTION_SEND or ACTION_VIEW and these intents won't return results.

see
https://developer.android.com/reference/android/content/Intent.html#ACTION_VIEW (output: nothing)
https://developer.android.com/reference/android/content/Intent.html#ACTION_SEND (output: nothing)

**Comment by EduardoIbarra** [comment]
It's been more than a year, has this got any fix yet? I'm facing this issue and my app cannot work properly without this callback triggering correctly on iOS.

**Comment by dbaq** [comment]
This issue is about Android. Android did not change it is way of handling callback. If you are having an iOS issue, feel free to open a new one.

**Comment by mrlonnie** [comment]
So is this issue considered working as intended/not going to fix/only Android OS can fix?  Running into the same issue with immediate success callback on the Android platform.

**Comment by dbaq** [comment]
hello @pixelpuffpastry, 

Yes, unfortunately nothing has changed over the years. Please refer to https://github.com/cordova-sms/cordova-sms-plugin/issues/26#issuecomment-86881976.

**Comment by mrlonnie** [comment]
Ah - thanks for the quick reply!

**Comment by Kevin-Hamilton** [comment]
@dbaq is [this](https://stackoverflow.com/questions/26090381/sending-sms-via-an-intent-and-know-if-the-sms-has-been-sent-or-not) a possible solution?

**Comment by dbaq** [comment]
That's interesting, definitely seems complex but would deserve some digging.

**Comment by umairrafiq1133** [comment]
@dbaq Any update on callback for android?

**Comment by dbaq** [comment]
@umairrafiq1133 nothing on the android front.

**Comment by dshark95** [comment]
Hi @dbaq any update on the android callback?

**Comment by dbaq** [comment]
hey @dshark95, as far as I know, it remains the same on Android.
