### ISSUE TITLE
SMS History

### ISSUE THREAD

**Issue by spyjo** [cordova-sms/cordova-sms-plugin#27]
Hello,

I was wondering if there is a way to tell to Android to not save the message sent with the empty intent ?
Actually when I send a message, it is saved directly in sms history in the sms app.

Thanks

**Comment by dbaq** [comment]
As far as I know, this is not possible. I might be wrong but I quickly looked for it and haven't find anything.

**Comment by dbaq** [comment]
I haven't found any options for that. I am closing this issue for now, feel free to reopen it if you have more information.
