### ISSUE TITLE
I am unable to send message in backend

### ISSUE THREAD

**Issue by satyagvns** [cordova-sms/cordova-sms-plugin#28]
Hello,

I started working on phone gap and I got requirement like, send sms in back end. I am trying your plugin. When I click on "send sms" button. It is opening hangouts. I tried both options available in your example. But I am unable to send back end.

Can you please help me in this.

Thanks,
Satya

**Comment by satyagvns** [comment]
I am generating apk using build.phone gap.com

It is giving me app-debug.apk. is debug blocking back end process? Just to clarify. Or am I doing any wrong?

**Comment by dbaq** [comment]
Hi @satyagvns,

I am sorry, I don't really understand the issue here. When you said "send sms in back end", are you talking about sending a text message from a server or directly from your app? 

If you don't want to open the default SMS application on android and directly send the text message, you have to let blank the INTENT option:

```
   var options = {
            android: {
                intent: '' // send SMS without opening any other app
            }
        };
```

**Comment by satyagvns** [comment]
I have tried this also... But it is opening my default message application

**Comment by satyagvns** [comment]
If you want I can share my sample code with you

**Comment by dbaq** [comment]
@satyagvns definitely, that would be very helpful.

**Comment by satyagvns** [comment]
@dbaq 
1. HTML CODE : https://github.com/shainfotech/abhaya/blob/master/www/index.html
2. JS CODE : https://github.com/shainfotech/abhaya/blob/master/www/js/index.js

I didn't change anything in Java code for android... I need this feature very badly... Could you please help me on this

**Comment by dbaq** [comment]
@satyagvns, are you using https://build.phonegap.com/plugins/1999?

I tagged a new version so you can have the latest version available on phonegap build.

Your code looks fine to me. So just wait for the new version on PB. It should be available tomorrow I think.

**Comment by satyagvns** [comment]
@dbaq, Yes. I am using that one only. Once the latest version available, do I need to checkout new one or pull request is enough to upgrade to new version.

Thanks,
Satya

**Comment by dbaq** [comment]
in your config.xml, you have the following line:

```
<gap:plugin name="com.cordova.plugins.sms" version="0.1.1" />
```

you will have to replace it by

```
<gap:plugin name="com.cordova.plugins.sms" version="0.1.2" />
```

or you can use

```
<gap:plugin name="com.cordova.plugins.sms"/>
```

but that this will result in your app being automatically updated with new versions of this plugin as they are released, and may result in unexpected behaviour.

**Comment by satyagvns** [comment]
@dbaq, Thanks for your information. I am eagerly waiting for that new version for sending sms in background

Thanks a lot for your precious help

**Comment by dbaq** [comment]
@aharris88 could you check if a tagged version is enough or if we have to upload a new version?

**Comment by agarrharr** [comment]
@dbaq Yes, I think so, but I think we need to leave the 0.1.1 version up, for people that haven't upgraded.

**Comment by satyagvns** [comment]
Today I will try with version 0.1.2 and let you know, If I face any problem

**Comment by satyagvns** [comment]
Unable to create app: plugin unsupported: com.cordova.plugins.sms @ 0.1.2 

I am getting this error while generating apk in build.phonegap.com

**Comment by agarrharr** [comment]
Phonegap Build didn't get the new version yet. I asked a question on their Google Group to find out how to make sure that it updates: https://groups.google.com/forum/#!topic/phonegap/2bWTxxu3j-k

**Comment by satyagvns** [comment]
Hi Team,

Thanks for your quick response. I will wait for your latest reply on this.

**Comment by agarrharr** [comment]
I just submitted the new version. Try now.

**Comment by satyagvns** [comment]
@aharris88 @dbaq

Thanks a lot for your support on this.

My Repo : https://github.com/shainfotech/abhaya

I am using build.phonegap.com to generate my apk file. My mobile is google nexus 5.

Still I am facing the same problem. it is opening my native message app (hangouts). Do I need to change anything in my phone settings? or anything I need to change in my code?

When I try to checkout latest git clone, I got below error:

# cordova plugin add https://github.com/cordova-sms/cordova-sms-plugin.git

Fetching plugin "https://github.com/cordova-sms/cordova-sms-plugin.git" via git clone
SyntaxError: Unexpected token ]
    at Object.parse (native)
    at Function.PlatformJson.load (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/PlatformJson.js:33:21)
    at runInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:257:37)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:81:16
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)

Thanks,
Satya

**Comment by satyagvns** [comment]
@dbaq @aharris88 

Any update. I need this plugin to be working. this feature is very important to my project.

Thanks,
Satya

**Comment by dbaq** [comment]
hey @satyagvns,

everything is fine for me when I am fetching the plugin

```
$ cordova plugin add https://github.com/cordova-sms/cordova-sms-plugin.git
Fetching plugin "https://github.com/cordova-sms/cordova-sms-plugin.git" via git clone
Installing "com.cordova.plugins.sms" for android
Installing "com.cordova.plugins.sms" for ios
```

```
$ cordova -v
4.2.0
```

Which version are you using?

**Comment by dbaq** [comment]
@satyagvns, are you still experiencing this issue?

**Comment by dbaq** [comment]
Closing this issue. Feel free to reopen it if you are still experiencing this issue.
