### ISSUE TITLE
How to prepopulate the message content in android?

### ISSUE THREAD

**Issue by Dineshrajaa** [cordova-sms/cordova-sms-plugin#29]
Hello all,
 I am trying to use this plugin in a test app which was successful in IOS(I mean the number and the message i am entering in the textbox is getting prepopulated in the native SMS Composer of IOS) but in Android its only populating the number field but the message is empty how can i fix this issue??

I took online build and tested and the plugin version i tried up is 0.1.2 and the Android platform version is Lollipop no issue with kitkat powered device,someone kindly help me to fix this issue.

**Comment by geri777** [comment]
+1 same issue, here.

**Comment by dbaq** [comment]
Hey guys, I just tried with the code on master (v.0.1.2) on my nexus 5 (with Lollipop). The text is displayed correctly in the hangout app with the code on the readme.
![2015-04-17 00 12 51](https://cloud.githubusercontent.com/assets/1867703/7194028/4343ea8e-e45d-11e4-8f89-bb3171f275ee.png)

Are you guys using phonegap build or cordova? Can you share some code please?

Thanks

**Comment by Dineshrajaa** [comment]
Ya sure I could share my code, kindly clone it from here https://github.com/Dineshrajaa/SMSManager.git . I am using Phonegapbuild and the problem was with Messaging app I didn't check in Hangout buddy.

**Comment by dbaq** [comment]
Could you check with hangout please? I am curious to know if it's working.

**Comment by dbaq** [comment]
Ok I cloned and used the repo you mentioned above with a regular cordova app (not via phonegap build). It works fine for Hangouts, Messaging, and Hello.

![2015-04-17 05 24 27](https://cloud.githubusercontent.com/assets/1867703/7196486/8c947b3e-e487-11e4-95dd-3d0b93c0cee3.png)

I am gonna see if I can create a phonegap app but I am not sure we can do it for free anymore.

**Comment by dbaq** [comment]
Ok, I forked the repo you mentioned and created a phonegap build (https://build.phonegap.com/apps/1412679/builds), can you download the APK file and try ? it is working for me.

**Comment by Dineshrajaa** [comment]
Just now tested your build https://build.phonegap.com/apps/1412679/builds still i couldn't get the message content populated in Messaging and another issue is i couldn't open Hangouts its directly taking me to Messaging app where the number is getting populated but not the message :(

**Comment by dbaq** [comment]
Hangouts needs to be the default sms app (in your phone preferences), to open normally.

which phone are you testing on? which exact version of android too please?

**Comment by Dineshrajaa** [comment]
I am testing on Samsung Galaxy S4 and its android version is 5.0.1

and in kitkat based mobile its prompting me to choose whether to open Hangout or Messaging but not in Lollipop powered device

**Comment by dbaq** [comment]
do you have any other android devices to test on?

**Comment by Dineshrajaa** [comment]
Hmm no buddy

**Comment by dbaq** [comment]
Are you still experiencing this issue? where you able to test on another device? it looks like it is a configuration on your lolipop device.

**Comment by Dineshrajaa** [comment]
At present I am not having any other android device powered by Android Lollipop will update this issue if i get one, thanks for keeping track of the bug report.

**Comment by dbaq** [comment]
Closing this issue. Feel free to reopen if you are still experiencing it on different devices.

**Comment by Dineshrajaa** [comment]
You can remove the bug tag, I have tested the same in a Cynogen 12 powered device and in that the message is getting prepopulated in Messaging app..

**Comment by dbaq** [comment]
Thanks for letting me know!
