### ISSUE TITLE
Windows "Universal" version

### ISSUE THREAD

**Issue by brody2consult** [cordova-sms/cordova-sms-plugin#31]
Should support Windows 8.0 (??)/Windows 8.1/Windows Phone 8.1

**Comment by brody2consult** [comment]
For Windows Universal, it is "cleanest" to do this purely in Javascript. As reported in litehelpers/Cordova-sqlite-storage#248, they need an immediate solution.

For Windows 8.0/8.1, it is possible to add DeviceCapabilities="sms" to the app manifest and use Windows.Devices.Sms.SmsDevice but this does _not_ work for me targeting Windows Phone 8.1. Ref:
- https://msdn.microsoft.com/en-us/library/windows.devices.sms.smsdevice.aspx
- https://code.msdn.microsoft.com/windowsapps/Sms-SendReceive-fa02e55e/sourcecode?fileId=44005&pathId=952808877

After a bit of searching, I found the following answer that works for Windows Phone 8.1 (but _not_ Windows 8.1): http://stackoverflow.com/questions/24894069/how-to-send-a-sms-message-from-within-an-windows-phone-8-1-app

Translated into Javascript:

``` Javascript
var cm = new Windows.ApplicationModel.Chat.ChatMessage();
cm.body = "test 1";
cm.recipients[0]="1234567";
Windows.ApplicationModel.Chat.ChatMessageManager.showComposeSmsMessageAsync(cm);
```

I also just discovered Windows.Devices.Sms.SmsDevice2 but not sure how and where it will work.

I am taking vacation in Poland this week, and am happy to integrate this for Windows 8.0, Windows 8.1, and Windows Phone 8.1 in 1-2 weeks.

**Comment by dbaq** [comment]
that would be a great addition! thanks

**Comment by dbaq** [comment]
Hey @brodybits, is there any chance that you will open a PR any time soon or should I close this one? Thanks.

**Comment by brody2consult** [comment]
My bad, I promised it 3 months ago. I still need a few weeks due to my own backlog. The good part is that it _should_ be pure JS for Windows "Universal" version. The bad part is that it does _not_ work the same way for Windows 8.1 and Windows Phone 8.1. I am also interested in whether or not it would be any different for Windows 10 (which is supposed to be the same for both desktop and phone).

I also suggest we consider keeping this open in case someone else gets a chance to work on this one.

**Comment by sohirani** [comment]
For using the universal api Windows.Devices.Sms.SmsDevice2, capability "cellularMessaging" needs to be included. While verifying the changes check if the device is unlocked: https://msdn.microsoft.com/library/windows/apps/xaml/dn706236.aspx. 

Here is the link for the sample application: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SmsSendAndReceive

**Comment by Vo2le** [comment]
Hi, i extended the Plugin for Windows 10 Universal Apps and in my testcases it worked quite well. I'm quite new to github. If i should upload the code i could need some guidance.

**Comment by dbaq** [comment]
Hey @Vo2le, thanks for considering contributing :+1: 

You should open a pull request. Take a look at https://help.github.com/categories/collaborating-on-projects-using-pull-requests/

**Comment by sachingarg2k1** [comment]
Hi guys,
When can we expect a new version with Universal App Support?

**Comment by brody2consult** [comment]
> When can we expect a new version with Universal App Support?

It is already there in PR #72. It has not been integrated since nobody has tested it yet. I am still on Visual Studio 2013 (Express) and am having trouble running the Windows Phone emulator so I cannot test it right now.

You can also get it from https://github.com/Vo2le/cordova-sms-plugin - (PR #72 was submitted from the master branch).

**Comment by brody2consult** [comment]
I tested PR #72 and am happy with the change.

**Comment by dbaq** [comment]
Closing this one since #72 has been merged.

**Comment by brody2consult** [comment]
> Closing this one since #72 has been merged.

Thanks for merging and releasing.
