### ISSUE TITLE
Sms.java:35: error: local variable args is accessed from within inner class; needs to be declared final

### ISSUE THREAD

**Issue by tobiasmuecksch** [cordova-sms/cordova-sms-plugin#33]
Hi guys.
I tried to build my App for Android. My App includes this plugin.

But the Build always fails with the following error:
`Sms.java:35: error: local variable args is accessed from within inner class; needs to be declared final`

Im using:
- Cordova 5.0.0
- cordova-sms-plugin: 0.1.3

I guess this plugin is not compatible with cordova 5.0

Will there be any 5.0 support?

**Comment by dbaq** [comment]
Hi @tobiasmuecksch,

Thanks for reporting the issue. I will try to look at it very soon.

**Comment by brody2consult** [comment]
@tobiasmuecksch for a quick fix: on line 27 (`public boolean execute(String action, JSONArray args, final CallbackContext callbackContext) throws JSONException`...) you should be able to just declare `JSONArray args` as `final` to make the compiler happy.

**Comment by dbaq** [comment]
Might be related to the merge of https://github.com/cordova-sms/cordova-sms-plugin/pull/32

**Comment by brody2consult** [comment]
> Might be related to the merge of #32

Yup

**Comment by tobiasmuecksch** [comment]
Thank you guys so much!

**Comment by dbaq** [comment]
That's my bad, I merged it without testing myself. I will try to find a moment tonight to fix it.

**Comment by brody2consult** [comment]
@tobiasmuecksch, you can use the following change to compile:

``` diff
$ git diff
diff --git a/src/android/Sms.java b/src/android/Sms.java
index 1cb1d1d..ce2480e 100644
--- a/src/android/Sms.java
+++ b/src/android/Sms.java
@@ -24,7 +24,7 @@ public class Sms extends CordovaPlugin {
        private static final String INTENT_FILTER_SMS_SENT = "SMS_SENT";

        @Override
-       public boolean execute(String action, JSONArray args, final CallbackContext callbackContext) throws JSONException {
+       public boolean execute(String action, final JSONArray args, final CallbackContext callbackContext) throws JSONException {

                if (action.equals(ACTION_SEND_SMS)) {
                        cordova.getThreadPool().execute(new Runnable() {
```

Haven't run it yet.

@dbaq please let me know if you want me to run a quick test (should be able to test it on my mobile) and issue a PR.

**Comment by dbaq** [comment]
That would be awesome! Thanks

**Comment by brody2consult** [comment]
Just tested on my mobile and issued the fix in PR #34

**Comment by tobiasmuecksch** [comment]
You guys are awesome!

**Comment by dbaq** [comment]
Well @brodybits is awesome! I merged the PR. Thanks!
