### ISSUE TITLE
iOS intent

### ISSUE THREAD

**Issue by Paul-Isache** [cordova-sms/cordova-sms-plugin#35]
Hi!
Is it possible to send a SMS from the app on iOS without exiting the app? I have tried the intent option but in doesn't work.
My phone runs on iOS 8.3.

Thanks! :)

**Comment by dbaq** [comment]
hi @Paul-Isache 

Unfortunately, it is not possible.

See readme:

```
Q: How can I send an sms in my iOS app without passing control to the native app like it can be done on Android?

A: This isn't possible on iOS. It requires that you show the user the native sms composer, to be able to send an sms.
```
