### ISSUE TITLE
phone number format

### ISSUE THREAD

**Issue by connor11528** [cordova-sms/cordova-sms-plugin#36]
I load in my contact's phone numbers and then send sms. The sms will send to some contacts but not others. I think it is due to how the contact's phone numbers are formatted.

415 279-5665    // will not send
+1 909-851-1662   // will send

What are the rules about formatting phone numbers in order to send sms?

**Comment by dbaq** [comment]
which platform?

**Comment by connor11528** [comment]
android

**Comment by dbaq** [comment]
there are pretty much no rule for that, are you using an intent or not?

**Comment by dbaq** [comment]
And please provide some code so I can reproduce. Thanks

**Comment by connor11528** [comment]
yeah you're right. I don't think the phone number matters. The code is standard:

```
            $cordovaSms
              .send(numberString, gifUrl, {})
              .then(function(res, b) {
                alert('Success sending SMS!');
              }, function(error) {
                alert('Error sending sms!')
              });
```

I get the success alert for every send. The sms sends from android to android but not android to iphone

**Comment by dbaq** [comment]
The success callback is fired when the SMS is sent not delivered. I never experienced or heard any issues about sending a SMS from android to iphone. Can you do more tests please?

**Comment by connor11528** [comment]
yeah will do. thanks for quick responses

**Comment by connor11528** [comment]
I added some options and I'm getting better behavior. Don't know why the sms was not delivered earlier:

`.send(number, gifUrl, {android: { intent: 'INTENT' }},`

**Comment by dbaq** [comment]
Interesting. So if you are using:
`.send(number, gifUrl, {android: { intent: '' }},`, it does not work?

**Comment by connor11528** [comment]
Sorry. Adding the options object helped me make sure the message was sent. This is an awesome plugin

**Comment by brody2consult** [comment]
> Adding the options object helped me make sure the message was sent.

@jasonshark can you be more specific about what options object you had to add? I suspect this can help many others. (It was a pain to solve these problems on the telco side!)

> This is an awesome plugin

Yeah!

**Comment by connor11528** [comment]
specifying the options object as the third parameter to the `.send()` method: `{android: { intent: '' }` helped make sure the message was delivered. Looking forward to MMS support so I can send the actual gif image instead of the gifUrl string
