### ISSUE TITLE
Message not sent on iOS 8.3

### ISSUE THREAD

**Issue by janie624** [cordova-sms/cordova-sms-plugin#39]
I tried to send message on iOS 8.3 but it's not working.
Here is my code;
    var success = function () { console.log('Message sent successfully'); };
    var error = function (e) { console.log('Message Failed:' + e); };
    var options = {
      replaceLineBreaks: false
    };

   sms.send(recipient.mobileNumber, $scope.message.body, options, success, error);
   console.log('end');

I can see log 'end' but cannot see success message or fail message.
How can I solve this?

**Comment by dbaq** [comment]
what are you using? Cordova? Phonegap? Ionic?

Are you sure the plugin is imported correctly?

**Comment by janie624** [comment]
Thanks for your reply.
I'm using both cordova and phonegap. I think that the plugin is installed correctly. I debugged it using Safari and it ran 

```
exec(
    success,
    failure,
    'Sms',
    'send', [phone, message, androidIntent, replaceLineBreaks]
);
```

and no any result.
I'm running my app using this command.
cordova run ios --device
What's wrong with me?

**Comment by dbaq** [comment]
are you using a simulator or real devices? 

AFAIK, it will work only on a real device.

**Comment by janie624** [comment]
I'm using my iPhone 5s.
Is there any other configuration I have to to before I run cordova run command?

**Comment by dbaq** [comment]
I just tested on iphone 6 with iOS 8.3, the message ui fired properly and the text message was sent and received.

can you test your code on an android device?

**Comment by dbaq** [comment]
are you sure that when you are calling sms.send, the deviceready event from cordova has been fired?

try something like that.

```
document.addEventListener('deviceready', function(e) {
  var success = function () { console.log('Message sent successfully'); };
  var error = function (e) { console.log('Message Failed:' + e); };
  var options = {
    replaceLineBreaks: false
  };

  sms.send('555555555', 'test', options, success, error);
}, false);
```

**Comment by janie624** [comment]
I'm sure I have called it after device ready.
I'm sorry but I have not setup android env right now.
Can you please check this repository to see what I am doing wrong? I'm a beginner with cordova indeed.
I appreciate your help. Thanks.

**Comment by dbaq** [comment]
this one https://github.com/sieraruo/notify?

**Comment by janie624** [comment]
yeah correct.

**Comment by dbaq** [comment]
Ok, I will have a look at it.

**Comment by janie624** [comment]
Message send function is in https://github.com/sieraruo/notify/blob/master/src/js/controllers.js.
Thanks again for your help.

**Comment by dbaq** [comment]
So I have tested your code on real devices (iphone 5s, nexus 5). The good news is that everything is working perfectly on both platforms.

The bad news is it's a configuration issue of your xcode project and that's annoying to find out :D

In xcode, make sure that `sms.m` is in compile sources. And make sure that `MessageUi.framework` is in Link binary with libraries.
![screen shot 2015-06-22 at 8 33 11 pm](https://cloud.githubusercontent.com/assets/1867703/8298838/59c5523e-1923-11e5-8b99-d0e0cf59443b.png)

**Comment by janie624** [comment]
Hi Didier,

Thanks for your effort. I really appreciate your help.

**Comment by janie624** [comment]
Hi Didier,
I could send sms by changing Xcode project settings.
Thanks a lot.

**Comment by dbaq** [comment]
Congrats!
