### ISSUE TITLE
How to read/list messages/sms?

### ISSUE THREAD

**Issue by rijine** [cordova-sms/cordova-sms-plugin#40]

**Comment by dbaq** [comment]
This plugin does not list/receive messages. It only sends SMS.

You can have a look at: https://github.com/dimitrismistriotis/ReadSmsCordovaPlugin

**Comment by rijine** [comment]
@dbaq : My question is y dont u add reading sms to this plugin?

**Comment by dbaq** [comment]
For feature request you can open an issue and explaining in details what you need.
