### ISSUE TITLE
ios should use a background thread

### ISSUE THREAD

**Issue by marcel-ernst** [cordova-sms/cordova-sms-plugin#43]
THREAD WARNING: ['Sms'] took '299.614014' ms. Plugin should use a background thread.

**Comment by dbaq** [comment]
Thanks for reporting that. I have starting the fix on this branch: https://github.com/cordova-sms/cordova-sms-plugin/tree/WIP_iOS_bg. I just need to test on a real iphone soon.

**Comment by dbaq** [comment]
The branch has been merged.
