### ISSUE TITLE
Support to read SMS

### ISSUE THREAD

**Issue by tusharbhatta** [cordova-sms/cordova-sms-plugin#44]
It would be a great addition to have support for reading SMS from the phone (android and other if supported).

**Comment by pungoyal** [comment]
:+1:

**Comment by dbaq** [comment]
I am considering adding this feature at one point. I believe other plugins are already doing the job. So upvote, if you want to be able to read SMS via this plugin.

**Comment by agarrharr** [comment]
Even if this feature were added, it would probably be better to add it as a separate repo in this organization. One reason is that it would mostly be completely separate code, and another is that it would probably require more permissions. And you should require as few permissions as possible.

**Comment by brody2consult** [comment]
> I am considering adding this feature at one point. I believe other
> plugins are already doing the job.
> So upvote, if you want to be able to read SMS via this plugin.

I would not upvote this feature unless it would work on iOS (which is not
possible if my memory serves me right).

**Comment by dbaq** [comment]
It won't happen in this plugin. Feel free to start another repo, I would be happy to reference it.
