### ISSUE TITLE
ios sms app

### ISSUE THREAD

**Issue by firaskudsy** [cordova-sms/cordova-sms-plugin#45]
hi, is there any way to send the sms in ios without opening the ios default sms app ? i mean send the sms in the background ?

thanks

**Comment by dbaq** [comment]
@firaskudsy, no it is not possible due to iOS restriction. Please see the readme for more information: https://github.com/cordova-sms/cordova-sms-plugin#how-can-i-send-an-sms-in-my-ios-app-without-passing-control-to-the-native-app-like-it-can-be-done-on-android
