### ISSUE TITLE
Sending Binary SMS

### ISSUE THREAD

**Issue by mattmarquard** [cordova-sms/cordova-sms-plugin#46]
Is it possible to use this plugin to send binary SMS instead of plain text? At first glance, it looks like it is hard coded although I didn't investigate too hard.

https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/android/Sms.java#L83

**Comment by dbaq** [comment]
The line you highlighted is only when you don't specify a phonenumber. Otherwise you should be able to pass everything you want I guess.

**Comment by mattmarquard** [comment]
I think you have to explicitly send the message using sendDataMessage() in order to send binary data, which would replace the call here: https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/android/Sms.java#L150 Unfortunately, I don't think the same API calls are available on the iOS platform which is a deal breaker for the use case I was going for.
