### ISSUE TITLE
Can not send multiple messages

### ISSUE THREAD

**Issue by avishayhajbi** [cordova-sms/cordova-sms-plugin#50]
when i try to send multiple messages only the firs one is complete.
 var options = {
      replaceLineBreaks: false,
      android: {
        intent: ''
      }
    };

$cordovaSms
      .send("123456,123456", new Date().getTime() ,options)
      .then(function() {
toast('Success');
        // Success! SMS was sent
      }, function(error) {
        toast('Error');
        // An error occurred
      });

**Comment by dbaq** [comment]
You can't do that. You can only specify multiple phone numbers with `intent: 'INTENT'` to start a MMS. 
In your case you have to iterate over you array of phonenumbers and call `$cordovaSms.send()` each time.
