### ISSUE TITLE
Unknown provider: $cordovaSmsProvider <- $cordovaSms

### ISSUE THREAD

**Issue by desmond-phonegap** [cordova-sms/cordova-sms-plugin#53]
I have added the cordova plugin and included the $cordovaSms to my controller. 

It is prompting "Unknown provider: $cordovaSmsProvider <- $cordovaSms".

Please help on what is missing part in this. Is there any javascript file that I need to refere.

**Comment by dbaq** [comment]
It is a regular Angular error when you forgot a step while installing ngCordova. Please follow http://ngcordova.com/docs/install/.

**Comment by dbaq** [comment]
I am closing this issue since no update. Feel free to reopen it if you still need help.
