### ISSUE TITLE
PhoneGap Plugins directory closing October 15th, 2015

### ISSUE THREAD

**Issue by danielmilner** [cordova-sms/cordova-sms-plugin#55]
Since the PhoneGap Plugins directory is being deprecated on October 15h, 2015, will this plugin soon be listed in the new Cordova Plugin NPM directory at http://plugins.cordova.io/npm/index.html ?

**Comment by dbaq** [comment]
Hi @danielmilner, 

Thanks for pointing this out. I am going to do it.

**Comment by dbaq** [comment]
Done. http://plugins.cordova.io/npm/index.html?q=cordova-sms-plugin

Feel free to reopen this issue if you have any questions.
