### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by ptarjan** [cordova-sms/cordova-sms-plugin#57]
Can you publish this plugin to NPM so we don't have to use git?

**Comment by dbaq** [comment]
It is already on NPM. https://www.npmjs.com/package/cordova-sms-plugin.

**Comment by ptarjan** [comment]
Great! Can you change the README to use that instead of git? Most people feel more comfortable with using releases instead of master

**Comment by dbaq** [comment]
That's a great idea. Done via 3fc6e45bd0e9132e234aa9596c18d526eb6d7bde.
