### ISSUE TITLE
Disable intent permission android

### ISSUE THREAD

**Issue by roblav96** [cordova-sms/cordova-sms-plugin#60]
Is there anyway I can disable the intent permission if I won't be using it? I don't like the permission on my app that says "this might cost you money" 

I'm only using the plugin to populate an SMS. Thank you!

**Comment by dbaq** [comment]
You can try to remove this line https://github.com/cordova-sms/cordova-sms-plugin/blob/master/plugin.xml#L28.

**Comment by roblav96** [comment]
Ah! that's exactly what I'm looking for! lol

I was google searching cordova plugin permissions but couldn't find anything on this. Thank you!!!

**Comment by dbaq** [comment]
Glad it worked :)
