### ISSUE TITLE
unfortunately, ....(app name) has stopped

### ISSUE THREAD

**Issue by beamthsa** [cordova-sms/cordova-sms-plugin#61]
When send sms it's show "unfortunately, ....(app name) has stopped"
I use send sms type >> intent: ''
I don't know how to fix this problem. 
Thank you for answer.

**Comment by rodneyworkman291** [comment]
+1

My app crashes on a phone that is running Android 5.1.  The message I receive is as stated above.  

Works well on IOS and on a Android 4.4.4

```
            document.addEventListener("deviceready", function () {
                sms.send(number, message, options, success, error);
            }, false);
```

**Comment by beamthsa** [comment]
I try to update android sdk then my app don't crash anymore.

You should update android sdk but not sure If update then app don't crash.

**Comment by dbaq** [comment]
Thanks @beamthsa for sharing your solution.
