### ISSUE TITLE
If is passed something vars on success callback it is called everytime (also on error)

### ISSUE THREAD

**Issue by trippo** [cordova-sms/cordova-sms-plugin#62]
If i pass something in the success callback it is called everytime also when there is an error.

example:

sms.send(data.phoneNumber, text, options, success(data), error );

success(data) is called also when there is an error...

**Comment by netbuffer** [comment]
And that ’ s happened to me

**Comment by dbaq** [comment]
which platform, which version of cordova? can you also share some code pls?

**Comment by trippo** [comment]
In last version of cordova on android 4.
Es. in a for cycle to send 10 sms i want to update the state of "to send sms".

var error = function(id){
//set id message to error
}
var success = function (id) { 
//set id message to sent
}
for ...
sms.send(phoneNumber, message, options, success(id), error(id) );

**Comment by ghost** [comment]
For android It is passing success even if the user cancels out and dose not sent SMS...i wrote a post on how to use this with ionic see code here 
http://pointdeveloper.com/how-to-send-an-sms-with-ionic-framework-and-ngcorodva/

i have tested it in Android 4.1 and 5 with 'INTENT' also without it.

Does the success call back refer to sending of SMS or just that the SMS app has been passed the data?

**Comment by dbaq** [comment]
Are you guys all using ngCordova?

**Comment by dbaq** [comment]
@pointdeveloper, please see #26.
@trippo I believe, you cannot do what you are doing.

``` diff
for (...) {
-  sms.send(phoneNumber, message, options, success(id), error(id) );
+  sms.send(phoneNumber, message, options, success, error);
}
```

You can't pass parameters to the `success` or `error` callback functions. Here is a SO post that might help you: http://stackoverflow.com/questions/13003828/javascript-callback-function-with-parameters

**Comment by trippo** [comment]
Thanks
