### ISSUE TITLE
how to add html tags in sms content?

### ISSUE THREAD

**Issue by PriyankaRose** [cordova-sms/cordova-sms-plugin#63]
I want to send app download link in sms. But when i give in <a href="link.com">appname</a>, the html tag is reflecting in sms without creating a link. Is it possible to allow html tags in sms?

**Comment by dbaq** [comment]
Hi @PriyankaRose,

AFAIK, SMS is text only. You can achieve that using a MMS. MMS is not supported yet. See #14 for more information.

**Comment by PriyankaRose** [comment]
Hi @dbaq 

First of all thanks for the reply ASAP. By giving the entire link in text, its automatically changes into a link in sms and on clicking, opens in browser. So my issue is solved. Thanks

**Comment by kuldipem** [comment]
@PriyankaRose , can you help me ? how you solved this issue ? I am also facing this issue ,

**Comment by PriyankaRose** [comment]
@kuldipem , there is no way of adding html coding in sms. add your app link, it will be converted to a link in your sms message.

**Comment by brody2consult** [comment]
I think the implication is that you should use shortened URLs, and use a URL shortening service if necessary. Just my $0.02 worth.

**Comment by dbaq** [comment]
Yes, you can have a HTTP link in the SMS content. Most of the SMS apps will transform that into a clickable link. But you can't put the HTML tag `a` in it. Also using shortened URLs is a good idea. Take a look at goo.gl.
