### ISSUE TITLE
Will the same JS file use for iOS build?

### ISSUE THREAD

**Issue by vishvendu** [cordova-sms/cordova-sms-plugin#64]
I'm using cordova 3.9.2 I tried to use the same sms.js to build an app for iOS but nothing is happening.

Do i need to change anything inside the sms.js file for ios ?

Thanks
Vishvendu Palawat

**Comment by dbaq** [comment]
Hey @vishvendu, yes it is the same file. Have you read this page (https://cordova.apache.org/docs/en/5.4.0/guide/cli/index.html)? Have you added other plugins to your application or is it the first one?
Which command did you enter to add the plugin?

I need more details if you want me to help you.

Cheers

**Comment by dbaq** [comment]
Closing this one since no answer.
