### ISSUE TITLE
Build iOS Error - Cordova v4.0.1

### ISSUE THREAD

**Issue by roblav96** [cordova-sms/cordova-sms-plugin#66]
I'm getting a build error on iOS.

![screen shot 2016-01-19 at 1 13 23 pm](https://cloud.githubusercontent.com/assets/1457327/12427657/7582383a-beae-11e5-8851-2abfc0ae4611.png)

I'm on the latest cordova ios v4.0.1

**Comment by dbaq** [comment]
Hey @roblav96,

I am going to take care of that in a couple of hours. I just need to push a new version on npm.

**Comment by roblav96** [comment]
Commenting it out fixes it.

like here:
https://github.com/sportstech/cordova-sms-plugin/commit/738beb39bd8a373cc01f94d4c4925a9a6df939b3

**Comment by dbaq** [comment]
it is already on master, just need to push a new version.

**Comment by dbaq** [comment]
The new version has been pushed on npm: https://www.npmjs.com/package/cordova-sms-plugin

**Comment by roblav96** [comment]
Thanks man!!
