### ISSUE TITLE
The plugin doesn't works on OSX El Capitan bot work on Maverick @ version 0.1.6

### ISSUE THREAD

**Issue by krittapaksil** [cordova-sms/cordova-sms-plugin#69]
The plugin doesn't works on OSX El Capitan, Xcode 7 and IOS 9.2 . I got error on Xcode 
at plugin version @0.1.6 and 0.1.7

[CDVCommandQueue executePending] [Line 159] FAILED pluginJSON = ["Sms1811732695","Sms","send",[["099-999-9999"]," ","INTENT",false]]

However I test it on : 
1. OSX Maverick is not works on version cordova-sms-plugin@0.1.7 but works on version @0.1.6 
2. Android all function is work on window and mac.

Thanks.

**Comment by dbaq** [comment]
Hey @krittapaksil,

check this out https://github.com/cordova-sms/cordova-sms-plugin/issues/39#issuecomment-114349417
