### ISSUE TITLE
How to receive SMS ?

### ISSUE THREAD

**Issue by Mcfloy** [cordova-sms/cordova-sms-plugin#70]
Hello,

I'd like to make an application that can emit SMS to a watch, and receive the answer of the watch (that send back automatic sms).

So just a receive function that have in parameters at least the phone number that we should get (and just ignore the others), and avoiding the user to have the SMS in his history...

Does this exist ?

**Comment by dbaq** [comment]
Hey @Mcfloy,

> How to receive SMS ?
> `cordova-sms-plugin` is send only, you can't read sms with it. Take a look at https://github.com/Pyo25/Phonegap-SMS-reception-plugin.
> 
> avoiding the user to have the SMS in his history
> You can't since you are sending the SMS on behalf of the user. You might be able to delete a specific test but not with this plugin.

Cheers.
