### ISSUE TITLE
Can't find error: sms

### ISSUE THREAD

**Issue by cfjedimaster** [cordova-sms/cordova-sms-plugin#71]
Plugin is installed - waiting for deviceready, and yet i get sms isn't defined.

**Comment by cfjedimaster** [comment]
Well, this is interesting. When you install the plugin via "cordova-plugin-sms", you do NOT get this plugin. Instead, you get this one: https://github.com/floatinghotpot/cordova-plugin-sms

**Comment by cfjedimaster** [comment]
And I apologize - I see one is cordova-sms-plugin and one is cordova-plugin-sms. _sigh_ :)

**Comment by agarrharr** [comment]
Hey Raymond. Thanks for putting in this issue! Your articles on cordova/phonegap were a great help to me when I originally put together this plugin.

**Comment by cfjedimaster** [comment]
You are most welcome. :) It was one of those articles that I just had to update. Switched it to this plugin.

**Comment by Yusadolat** [comment]
Sir @cfjedimaster what do we Install Instead?

**Comment by cfjedimaster** [comment]
I don't remember - I think cordova-sms-plugin. Try both - it won't take you long. ;) Or ask @dbaq

**Comment by Yusadolat** [comment]
Okay sir thanks.

**Comment by dbaq** [comment]
hey @Yusadolat, you should install via `cordova-sms-plugin`:

`cordova plugin add cordova-sms-plugin`

**Comment by HimanshuHD** [comment]
I think 'corodva-sms-plugin' does not provide all native messaging functionalities. It only gives send  functionality. While on the other side, 'cordova-plugin-sms' gives us multiple native functionalities like sendSMS, listSMS, deleteSMS, startWatch, stopWatch and few more. I want to implement autofill OTP on arrival of SMS, and 'cordova-plugin-sms' has 'startWatch' and 'onSMSArrive' event to implement the same, but getting some typescript issues. Can anyone please help ?
 Thanks in ADVANCE.

**Comment by dbaq** [comment]
You should use the other plugin then, this one is for read only. Please open an issue on their repository.

**Comment by syedehsans1** [comment]
I have installed both sms-plugin and plugin-sms. I am still getting the same issue

**Comment by cfjedimaster** [comment]
Which issue?

**Comment by matusiam34** [comment]
> I have installed both sms-plugin and plugin-sms. I am still getting the same issue

I am getting the same thing. I have spent the entire day today trying to send a text message and it is driving me nuts plus I am questioning my sanity at this point :)

**Comment by goidimo** [comment]
I'm getting  the below error:

Uncaught ReferenceError: sms is not defined
    at Object.sendSms

any suggestions pls.

**Comment by syedehsans1** [comment]
You will get this error on browser console. It works fine on device and
simulators.
