### ISSUE TITLE
Marshmallow Permission

### ISSUE THREAD

**Issue by stevecarlton** [cordova-sms/cordova-sms-plugin#75]
Hi there,

I seem to be getting a decent amount of crashes due to permissions on sending SMS messages with this plugin. 
`"Fatal Exception: java.lang.SecurityException: Sending SMS message: uid 10238 does not have android.permission.SEND_SMS"`

Most of the crashes are on Marshmallow, I am assuming due to the new runtime permissions implemented in Android M. Are there any plans to have the plugin request permission (or am I missing something?)

**Comment by dbaq** [comment]
Hi @stevecarlton,

Thanks for reporting this issue. Can you provide a more detailed crash report? That would be really helpful.

>  Are there any plans to have the plugin request permission (or am I missing something?)

Yes, I am busy at work right now but I am going to try to implement this by the end of next week.

**Comment by stevecarlton** [comment]
@dbaq I do hope this helps:
`Fatal Exception: java.lang.SecurityException: Sending SMS message: uid 10267 does not have android.permission.SEND_SMS.
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.os.Parcel.readException(Parcel.java:1573)
       at com.android.internal.telephony.ISms$Stub$Proxy.sendTextForSubscriber(ISms.java:1577)
       at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:380)
       at android.telephony.SmsManager.sendTextMessage(SmsManager.java:333)
       at com.cordova.plugins.sms.Sms.send(Sms.java:150)
       at com.cordova.plugins.sms.Sms.access$200(Sms.java:22)
       at com.cordova.plugins.sms.Sms$1.run(Sms.java:58)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by dbaq** [comment]
hey @stevecarlton, just a quick update here. I am still working on it. The good news is that I've been able to reproduce on my nexus 5. Keep you posted soon.

**Comment by dbaq** [comment]
@stevecarlton, would you mind testing this branch https://github.com/cordova-sms/cordova-sms-plugin/compare/android-request-permission ? 

Nothing changes for you. If the app does not have the permission to send a SMS, the permission will be automatically requested. I also exposed a new function `sms.hasPermission(function(hasPermission) {..}, function(error) {..})`, if you want to display an explanation text before requesting the permission and sending the first SMS.

Let me know.
Cheers,

**Comment by stevecarlton** [comment]
@dbaq You are awesome. Just tested and all seems well. I did not however test the new function. `sms.hasPermission(function(hasPermission) {..}, function(error) {..})`

I will also dig out my Lollipop phone here in a few minutes for a bit of regression testing.

**Comment by dbaq** [comment]
hey @stevecarlton, thanks for deep testing it. Let me know if you find anything, you should need at least cordova-android 5.1.1 (`cordova platform update android@5.1.1`).

The `hasPermission` function is straightforward, no need to really test it.

Keep me posted.

**Comment by stevecarlton** [comment]
Tested a bit more today with no issues. Lollipop is unchanged and for Marshmallow the prompt is perfect. Thanks for all you do to support the plugin @dbaq

**Comment by dbaq** [comment]
Glad to hear that, I am going to merge this branch on master, let it sit there for a few days then publish a new release. Will close the issue after posting the new release.

**Comment by dbaq** [comment]
I published a new release and updated the readme file via https://github.com/cordova-sms/cordova-sms-plugin/commit/d3df32b263ad72a00a58c3ac0cbfd787ff599ab7.

Closing this issue for now. Feel free to open a new one if you notice anything. Thanks again for testing. :beers:
