### ISSUE TITLE
My App crash when use intent: ''

### ISSUE THREAD

**Issue by Neotrixsx** [cordova-sms/cordova-sms-plugin#78]
I'm having some trouble with SMS plugin from ngCordova. If I send a message with the intent option set to 'INTENT', everything works fine, prompting the SMS application installed. But, when I set intent to ' ' (to use android's native SMS sender), my app crashes. Here's the code:

```
  $scope.sms = {};
    var options = {
        replaceLineBreaks: false, // true to replace \n by a new line, false by default
        android: {
            intent: '' // send SMS with the default SMS app
        }
    };
    $scope.smsSend = function () {
        console.log($scope.sms.phno);
        console.log($scope.sms.msg);
        document.addEventListener("deviceready", function () {
            $cordovaSms
                .send($scope.sms.phno, $scope.sms.msg, options)
                .then(function () {
                    // Success! SMS was sent
                    console.log('Success');
                }, function (error) {
                    // An error occurred
                    console.log(error);
                }); //then
        });
    };
```

**## Testing OS : Marshmallow Android**

**Comment by dbaq** [comment]
Can you give me the android stacktrace pls? You can easily find it with `$ adb logcat` (more info here http://developer.android.com/tools/help/logcat.html)

Also, I published a new release a few days ago, make sure you have the latest version (0.1.10)

**Comment by Neotrixsx** [comment]
I update plugin to the latest version (0.1.10) and I add hasPermission check but  every time I get "hasPermission: false" in my console and when my app start its not ask me any Permission for SMS. Is it any possibility to ask permission from user for SMS manually.

**Comment by dbaq** [comment]
Ok, can you please give me the android stacktrace. You can use `$ adb logcat` for that.

**Comment by webarchymeta** [comment]
I had the same issue, but it disappeared after upgrading to version 0.1.10

**Comment by Neotrixsx** [comment]
I did some changes in my code. Now its working fine.:)

**Comment by dbaq** [comment]
Glad you found out 👍

**Comment by coolbeatz71** [comment]
Please have you done to solve this issues, because i am facing the same problem. My app crash after sending sms using intent:''. I am testing it on a real device android 5.1.1
