### ISSUE TITLE
send sms to multiple numbers example

### ISSUE THREAD

**Issue by dbaq** [cordova-sms/cordova-sms-plugin#8]
@ninapratiwi reported: ```Hi,

is there any example to send a sms to multiple numbers?

Cheers :)```

**Comment by dbaq** [comment]
@ninapratiwi, you can enter a list of phone numbers separated by commas.

for instance:

```
sms.send('4155551234,4151234567', message, intent, success, error);
```

**Comment by rohananarse** [comment]
does this work..?

sms.send('4155551234,4151234567', message, intent, success, error);
