### ISSUE TITLE
no npm registery for plugin?

### ISSUE THREAD

**Issue by GeoffreyEmery** [cordova-sms/cordova-sms-plugin#81]
Hey,
   When i run the second command in the readme. 
       # now add plugin
      cordova plugin add com.rjfun.cordova.smsh
The following error is shown
![2016-05-05_7-42-00](https://cloud.githubusercontent.com/assets/3301804/15046513/efc2afb4-1294-11e6-8014-10dd2e04767a.png)

**Comment by agarrharr** [comment]
This is the second command in the readme:

```
cordova plugin add https://github.com/cordova-sms/cordova-sms-plugin.git
```

It looks like you're running a different command. Can you try again with this command?

**Comment by GeoffreyEmery** [comment]
ok i see i was using a different repo so that was my bad. yours is working fine
i did find a another bug ...
Android blocks inline calls so you need to add a id and remove the direct call to the form
            <input type="button" id="sendSMS" value="Send SMS" />
and then add a listener in the app start up some where ape dd
        document.getElementById("sendSMS").addEventListener("click", app.sendSms);
That gets you past the permision issue i got on android 6.
----> new topic
when i applied this i felt like i was going to send sms from the app not open the default sms app. not sure if this was the intedended use case but was not quite what i was looking for.

**Comment by dbaq** [comment]
> Android blocks inline calls so you need to add a id and remove the direct call to the form

you probably need the whitelist cordova plugin

> when i applied this i felt like i was going to send sms from the app not open the default sms app. not sure if this was the intedended use case but was not quite what i was looking for.

Don't get this point. You can pass options to send directly the SMS or open the default sms app. Please read the readme file.

**Comment by GeoffreyEmery** [comment]
hey Didier, 
  Great picture and thanks for the fast response. : 

> Android blocks inline calls so you need to add a id and remove the direct call to the form
> you probably need the whitelist cordova plugin

it wasn't plugin whitelisting it was because the default content security was to strict this works.
 `
<meta http-equiv="Content-Security-Policy" content="default-src *;
        style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'">`

> when i applied this i felt like i was going to send sms from the app not open the default sms app. not sure if this was the intedended use case but was not quite what i was looking for.
> Don't get this point. You can pass options to send from the app directly. I would also add a note that ios  SMS will only send from the default sms app. Please read the readme file. 

The point is that when we develop apps to send sms we don't want to open the sms app to send them  by default my recomendation is to change the default to send and adding a note that ios doesn't allow this although i don't think this is true.
`//CONFIGURATION
        var options = {
            replaceLineBreaks: false, // true to replace \n by a new line, false by default
            //note: ios can not send message without opening the default message app
            android: {
                //intent: 'INTENT'  // send SMS with the native android SMS messaging
                intent: '' // send SMS without open any other app
            }
        };
`

Thanks again for the quick response hope the feedback helps.
please close issue.

**Comment by GeoffreyEmery** [comment]
solved
