### ISSUE TITLE
SMS platform not supported

### ISSUE THREAD

**Issue by TestAccount9691** [cordova-sms/cordova-sms-plugin#82]
On samsung Tab2(android v: 4.4.2) , TAB4(android v: 4.2.2)  and motoE(android v: 4.4.4) .Its not working and giving an error **"SMS platform not supported"**

**Comment by dbaq** [comment]
You can investigate this method:

https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/android/Sms.java#L113-L116

**Comment by dbaq** [comment]
Hi @TestAccount9691,

Any updates?

**Comment by TestAccount9691** [comment]
Yes.

In Samsung TAB 3 and TAB 4  the **FEATURE_TELEPHONY**  is not supported and always returns **false**  that's why i m getting an error **SMS platform not supported**.

In Samsung devices especially on **Tablets** its not considering as telephone.

Can you please suggest me any other way to use **ctx.getPackageManager().hasSystemFeature(PackageManager.FEATURE_TELEPHONY);** so that i doesn't that error.

Thanks in advance.

**Comment by dbaq** [comment]
Hi @TestAccount9691,

Can you try this http://stackoverflow.com/a/16346586/1039265 and let me know?

**Comment by DevendraSinghNagar** [comment]
Hi @TestAccount9691 
Can you try this plugin
https://github.com/DevendraSinghNagar/cordova-sms-all-devices-plugin

**Comment by dbaq** [comment]
Closing this one since no answer. Feel free to reopen it.
