### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by zeeshanjan82** [cordova-sms/cordova-sms-plugin#84]
I have a question, I think this plugin only works for Android API level 23 and above, which means the app will only get installed on latest android phones. I would like to have the app run on Android with API level 17 and above. Any Idea?

**Comment by dbaq** [comment]
Hey @zeeshanjan82.

You should be able to skip the call to `hasPermission()` here https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/android/Sms.java#L41-L42. 

Pull requests are welcomed :)

**Comment by spyjo** [comment]
Cordova released this plugin for permissions compatibility:
https://github.com/apache/cordova-plugin-compat
not sure if it can help somehow here, I did not try it for now

**Comment by dbaq** [comment]
Thanks @spyjo, it looks like a great solution. @zeeshanjan82 can you give a try?

**Comment by dbaq** [comment]
Closing this one, feel free to reopen it if the solution mentioned above si not working for you.
