### ISSUE TITLE
Installing on iOS

### ISSUE THREAD

**Issue by zeeshanjan82** [cordova-sms/cordova-sms-plugin#85]
I am trying to install the plugin on the Mac machine however I get the error: Cannot find plugin.xml for plugin 'org.apache.cordova.plugin.sms'

**Comment by agarrharr** [comment]
What command did you run to install?

**Comment by zeeshanjan82** [comment]
sudo cordova plugin add cordova-sms-plugin

**Comment by agarrharr** [comment]
Works fine for me on a mac.

![screen shot 2016-05-10 at 9 38 37 am](https://cloud.githubusercontent.com/assets/3266363/15152578/05e71c92-1693-11e6-8210-926993246951.png)

@dbaq Do you have any ideas?

**Comment by dbaq** [comment]
Same as you @aharris88. I can't reproduce the problem.

A few hints:
- make sure you have the latest version of cordova (`npm install -g cordova`) and cordova-ios
- avoid `sudo` when executing cordova commands

can you give us the full stacktrace as well please.

Cheers

**Comment by spyjo** [comment]
this may be related to this ?

https://cordova.apache.org/news/2016/01/28/tools-release.html

"Removed support for our old Cordova Plugins Registry. Now plugins can only be installed via npm, git URL or local paths."

may be you are linked to the old url / old version ?

**Comment by zeeshanjan82** [comment]
I am getting the following error after trying 'npm install -g cordova' also if I don't use 'sudo' then I get a Permission Denied error.
![cordova](https://cloud.githubusercontent.com/assets/8342604/15176155/4eed7b30-1787-11e6-8582-070b7090e0e4.png)

**Comment by dbaq** [comment]
> this may be related to this ?
> https://cordova.apache.org/news/2016/01/28/tools-release.html
> "Removed support for our old Cordova Plugins Registry. Now plugins can only be installed via npm, git URL or local paths."
> may be you are linked to the old url / old version ?

We are using NPM and not cordova plugins registry: https://www.npmjs.com/package/cordova-sms-plugin

@zeeshanjan82, two things to try here:

1- `cordova plugin rm cordova-sms-plugin && cordova plugin add cordova-sms-plugin`
2- check out http://stackoverflow.com/a/30299721/1039265

**Comment by dbaq** [comment]
since you open #86, I am assuming that you installed it correctly on iOS. Feel free to reopen it.

**Comment by zeeshanjan82** [comment]
I have analyzed more on this, actually the reason is very strange, there is no plugin with the name : org.apache.cordova.plugins.sms I cannot see any plugin in the ios.json file inside plugins folder. I am not sure from where it is taking this name. I had the sms plugin install previously but then I had removed it from the plugins folder as well as removed its reference from ios.json file also the name of that plugin was com.cordova.plugins.sms I don't know from where it is picking up org.apache.cordova.plugins.sms

**Comment by zeeshanjan82** [comment]
the strange thing is even when I try to remove any other plugin I get the same error : Cannot find Plugin.xml for the plugin org.apache.cordova.plugins.sms

**Comment by zeeshanjan82** [comment]
Ahh I was able to resolve this issue, I first removed android platform from mac and then fixed the issues related to the cordova , cordova-ios version and the issue got resolved.
