### ISSUE TITLE
SMS not working on iOS

### ISSUE THREAD

**Issue by zeeshanjan82** [cordova-sms/cordova-sms-plugin#86]
I am trying to run the code very similar to what is defined in this tutorial: https://github.com/cfjedimaster/Cordova-Examples/blob/master/smscomposer/www/js/app.js  However when I run the app in the iphone simulator I get the error 'SMS Text not available' (I have attached the screenshot with this issue). As I understand may be this issue is coming because of the simulator so I tried to run the app on an actual iphone and the SMS does not get send. There is no error which is logged in the safari console so I am really finding it difficult to know why the SMS plugin is not working on iOS the same code works file on android though.
![sms_issuepng](https://cloud.githubusercontent.com/assets/8342604/15359743/4fbde10c-1d28-11e6-89d2-e3686a0c2cc0.png)

**Comment by dbaq** [comment]
hi @zeeshanjan82, 

you should look in xcode if you have a stacktrace

**Comment by dbaq** [comment]
Closing this since no answer, feel free to reopen it.
