### ISSUE TITLE
READ_PHONE_STATE permission exception (Android Marshmallow)

### ISSUE THREAD

**Issue by lemouta** [cordova-sms/cordova-sms-plugin#87]
When i try to send a sms, i got this exception: java.lang.SecurityException: getGroupIdLevel1: Neither user 10185 nor current process has android.permission.READ_PHONE_STATE.

I'm using android marshmallow and the plugin's version is 0.1.10.
I guess the plugin is requesting only SEND_SMS permission, but I'm not a Java expert.

Has anyone experienced that?

**Comment by dbaq** [comment]
Hey @lmouta, I've never seen this exception. Have you figure this out?

**Comment by dbaq** [comment]
Closing this one since no reply. Feel free to reopen it.
