### ISSUE TITLE
Success callback fired on Android when SMS not sent (not using INTENT)

### ISSUE THREAD

**Issue by ibcomputing** [cordova-sms/cordova-sms-plugin#91]
There seems to be a long-standing issue where the success callback is always fired even if the SMS is not sent (for example there is no network available). I am **not** using INTENT, but trying to send the SMS _directly_, so I would expect the failure callback to fire if there is no network available for sending a SMS.
This issue was apparent in the earlier versions so I wrote a separate plugin to detect whether there was a network available before sending a SMS. As the plugin is a few version on, I thought I would revisit this, but still finding the same issue.

Update: Just been testing this some more and found out that the SMS messages that I thought had not been sent despite the success callback being called had been sent after all.
The cause for the confusion seems to be that sometime sent messages are recorded in the default SMS application's sent items and sometimes they are not.

**Comment by dbaq** [comment]
hey @ibcomputing,

the error verification is done here: https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/android/Sms.java#L157-L160, so it should be fine.

> The cause for the confusion seems to be that sometime sent messages are recorded in the default SMS application's sent items and sometimes they are not.

so is it a valid issue or not?

**Comment by ibcomputing** [comment]
Error callback code looks good. I will do some more testing to be sure, but at this point I don't think there is an issue. Sorry for wasting your time and thanks!

**Comment by dbaq** [comment]
No worries. I am closing this issue for now. Reopen it if you find anything.
