### ISSUE TITLE
Logs show "Message Cancelled" |  sms no longer working for iOS

### ISSUE THREAD

**Issue by shotbyabel** [cordova-sms/cordova-sms-plugin#94]
First the Email composer plugin would not open the iPhones email and then href-tel would not launch the call like before. I found a fix for both of these! 

```
  <access origin="mailto:*" launch-external="yes"/>
  <allow-intent href="tel:*" />

```

How ever it appears that `<access origin="sms:*" launch-external="yes"/>` does NOT do the trick for the sms plugin. I have tried different combinations and nothing seems to do the trick. The SMS app starts to open than it just closes abruptly and I get the "Message Cancelled" log in the console.

I can't seem to find a fix for this. My iphone is iOS 9.3.2 
and here are my Ionic settings..

Cordova CLI: 6.1.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by dbaq** [comment]
Hello @shotbyabel,

Please share some code. You should not have to use `sms:`. You should use `sms.send(number, message, options, success, error);`

**Comment by dbaq** [comment]
Closing this one since no replies. Feel free to reopen if if you are still having the issues.

**Comment by kuebel** [comment]
That does happen if you set number to null in js. Set it to ''.

**Comment by enesaltinkaya** [comment]
Also happens if the number is integer.

Make sure it is string.

sms.send(number, message, options, success, error);

**Comment by andreszs** [comment]
@nsfnd Thank you so much for that feedback, I had the same issue on iOS 10.3.3 and converting the number to string fixed everything. **+10**
