### ISSUE TITLE
IOS error Method 'sendSMS:' not defined in Plugin 'SMS'

### ISSUE THREAD

**Issue by marcellocolombo** [cordova-sms/cordova-sms-plugin#97]
Hi, I am triyng to send an sms from my cordova application using an ios 4s, but i get always get this error "ERROR: Method 'sendSMS:' not defined in Plugin 'SMS'
2016-08-10 15:49:58.732 EP[21038:60b] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["SMS487387103","SMS","sendSMS",[["366545XXXX"],"Set SMSinterval = 12"]]"...
But into plugin folder there are ios Sms.h and Sms.m files...

What must i check to understand if the plugin is corrected installed?
How can i solve this problem? Thank's

**Comment by dbaq** [comment]
For those having the issue, check in xcode that all the `.h` files are included.

Feel free to reopen it if you can figure it out.
